import { Hono } from 'hono'
import type { Context } from 'hono'
import { streamSSE } from 'hono/streaming'
import { prisma } from './src/lib/db'
import { notifyPendingMatches, recentMatches, scanDealAlerts } from './src/lib/alerts'
import { publish, subscribe, streamStatus, recentMessages } from './src/lib/events'
import { detectDeals } from './src/lib/deals'
import { findCommunityByName, invalidateCommunityCache } from './src/lib/community-match'
import { runHourlyRefresh, recentCronRuns, HOURLY_JOB } from './src/lib/cron'
import {
  runIntelligencePipeline, computeYieldCurve, migrationSurges, applyScenario,
  computeRealPriceIndex, computeBuildingProfiles, computeSupplyPipeline,
  computeInstitutionalFlow, computeMigrationSignal, computeDistrictMetrics,
  computeMarketSummary, ALL_BEDS,
} from './src/lib/intelligence'
import { fetchAllMacro, fetchExchangeRates } from './src/lib/macro'

const app = new Hono()

// ─── CORS ────────────────────────────────────────────────────────────────────
//
// This lives here, not only in server.tsx, because server.tsx is REGENERATED
// whenever prisma/schema.prisma changes — which silently reverted the copy there
// during this work. custom-routes.ts is never regenerated, so this is the durable
// place for cross-cutting API middleware.
//
// No wildcard in production. `Access-Control-Allow-Origin: *` lets any site read
// this API using the visitor's cookies, and it cannot be combined with
// credentials. In development the permissive behaviour is kept so local tooling
// is unchanged.
const ALLOWED_ORIGINS = ['https://sqftlab.com', 'https://www.sqftlab.com']

app.use('*', async (c, next) => {
  const origin = c.req.header('Origin') ?? ''
  const isProd = process.env.NODE_ENV === 'production'
  const allowed = !isProd || ALLOWED_ORIGINS.includes(origin)

  if (c.req.method === 'OPTIONS') {
    if (allowed) {
      c.res.headers.set('Access-Control-Allow-Origin', isProd ? origin : '*')
      c.res.headers.set('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS')
      c.res.headers.set('Access-Control-Allow-Headers', 'Content-Type,Authorization')
      c.res.headers.set('Access-Control-Max-Age', '86400')
      if (isProd) c.res.headers.set('Vary', 'Origin')
    }
    return c.text('', 204)
  }

  await next()

  // Applied AFTER next() so the headers land on the handler's final response.
  // Setting them before next() writes to a response object the handler then
  // replaces, which is why the wildcard could survive the earlier fix.
  if (allowed) {
    c.res.headers.set('Access-Control-Allow-Origin', isProd ? origin : '*')
    c.res.headers.set('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS')
    c.res.headers.set('Access-Control-Allow-Headers', 'Content-Type,Authorization')
    // Reflecting the Origin makes the response vary by it; without Vary a shared
    // cache could hand one origin's response (and its CORS headers) to another.
    if (isProd) c.res.headers.set('Vary', 'Origin')
  } else {
    // server.tsx is regenerated by the SDK and its generated copy re-adds
    // `Access-Control-Allow-Origin: *` on every route — including /api. Deleting
    // it here is what actually makes the policy hold: without this, a disallowed
    // origin still received the wildcard alongside the API response.
    c.res.headers.delete('Access-Control-Allow-Origin')
    c.res.headers.delete('Access-Control-Allow-Methods')
    c.res.headers.delete('Access-Control-Allow-Headers')
    c.res.headers.set('Vary', 'Origin')
  }
})

// ─── Health & diagnostics ─────────────────────────────────────────────────────

// Report the *shape* of DATABASE_URL without leaking credentials. The literal
// "${{Postgres.DATABASE_URL}}" string is the classic Railway misconfiguration:
// the placeholder was written as a value instead of resolved as a reference.
function redactDbUrl(raw?: string) {
  if (!raw) return 'unset'
  if (raw.startsWith('${{')) return `UNRESOLVED_PLACEHOLDER:${raw}`
  try {
    const u = new URL(raw)
    return `${u.protocol}//${u.username ? '***@' : ''}${u.host}${u.pathname}`
  } catch {
    return `malformed:${raw.slice(0, 16)}`
  }
}

// Readiness probe — reports real DB connectivity plus the resolved error, so a
// misconfigured database surfaces as readable JSON instead of an empty site.
app.get('/health/db', async (c) => {
  const url = redactDbUrl(process.env.DATABASE_URL)
  try {
    const communities = await prisma.community.count()
    const listings = await prisma.listing.count()
    return c.json({ ok: true, db: 'connected', url, communities, listings })
  } catch (e) {
    return c.json(
      { ok: false, db: 'unreachable', url, error: e instanceof Error ? e.message : String(e) },
      503,
    )
  }
})

// ─── Communities ──────────────────────────────────────────────────────────────

app.get('/sqftlab/communities', async (c) => {
  const emirate = c.req.query('emirate')
  const search = c.req.query('search')
  const where: Record<string, unknown> = {}
  if (emirate && emirate !== 'all') where.emirate = emirate
  if (search) where.nameEn = { contains: search }

  const communities = await prisma.community.findMany({
    where,
    orderBy: { medianAedSqft: 'desc' },
    select: {
      id: true, slug: true, nameEn: true, nameAr: true, emirate: true,
      latitude: true, longitude: true, medianAedSqft: true, medianAnnualRentAed: true,
      grossYieldPct: true, neighbourhoodScore: true, priceChange30d: true,
      priceChange1y: true, transactionCount30d: true, totalTransactions: true,
      scoreSchools: true, scoreHealthcare: true, scoreMetro: true,
      scoreRetail: true, scoreParks: true, scoreWorship: true,
    },
  })

  // Per-district deal count, for the heatmap's Deals layer and the district
  // side panel. One grouped query rather than a count per community, which
  // would be N+1 across every district.
  const dealGroups = await prisma.listing.groupBy({
    by: ['communityId'],
    where: { isDeal: true },
    _count: { _all: true },
  })
  const dealsByCommunity = new Map(dealGroups.map((g) => [g.communityId, g._count._all]))

  return c.json({
    communities: communities.map((c) => ({ ...c, dealCount: dealsByCommunity.get(c.id) ?? 0 })),
  })
})

app.get('/sqftlab/communities/:slug', async (c) => {
  const slug = c.req.param('slug')
  const community = await prisma.community.findUnique({
    where: { slug },
    include: {
      listings: { where: { purpose: 'sale' }, orderBy: { listedAt: 'desc' }, take: 10 },
      _count: { select: { transactions: true, listings: true } },
    },
  })
  if (!community) return c.json({ error: 'Community not found' }, 404)
  return c.json({ community })
})

app.get('/sqftlab/communities/:slug/transactions', async (c) => {
  const slug = c.req.param('slug')
  const page = parseInt(c.req.query('page') || '1')
  const limit = parseInt(c.req.query('limit') || '50')
  const propertyType = c.req.query('type')
  const beds = c.req.query('beds')

  const community = await prisma.community.findUnique({ where: { slug } })
  if (!community) return c.json({ error: 'Community not found' }, 404)

  const where: Record<string, unknown> = { communityId: community.id }
  if (propertyType) where.propertyType = propertyType
  if (beds) where.beds = parseInt(beds)

  const [transactions, total] = await Promise.all([
    prisma.transaction.findMany({
      where,
      orderBy: { transactionDate: 'desc' },
      skip: (page - 1) * limit,
      take: limit,
    }),
    prisma.transaction.count({ where }),
  ])

  return c.json({ transactions, total, page, limit, pages: Math.ceil(total / limit) })
})

app.get('/sqftlab/communities/:slug/listings', async (c) => {
  const slug = c.req.param('slug')
  const purpose = c.req.query('purpose') || 'sale'
  const beds = c.req.query('beds')
  const dealsOnly = c.req.query('deals') === 'true'

  const community = await prisma.community.findUnique({ where: { slug } })
  if (!community) return c.json({ error: 'Community not found' }, 404)

  const where: Record<string, unknown> = { communityId: community.id, purpose }
  if (beds) where.beds = parseInt(beds)
  if (dealsOnly) where.isDeal = true

  const listings = await prisma.listing.findMany({
    where,
    orderBy: { listedAt: 'desc' },
    take: 50,
  })
  return c.json({ listings })
})

// ─── Price trend (real DLD transaction aggregation) ──────────────────────────

// `Transaction.transactionType` stores lowercase values (`sale`,
// `off_plan_sale`, `mortgage`). The spec's SQL sample filtered on 'Sales',
// which matches no row in this schema.
const SALE_TXN_TYPES = ['sale', 'off_plan_sale']

app.get('/sqftlab/communities/:slug/trend', async (c) => {
  const slug = c.req.param('slug')
  const period = c.req.query('period') || '12m'
  const community = await prisma.community.findUnique({ where: { slug } })
  if (!community) return c.json({ error: 'Community not found' }, 404)

  const months = period === '5y' ? 60 : period === '3y' ? 36 : 12
  const since = new Date()
  since.setMonth(since.getMonth() - months)

  const transactions = await prisma.transaction.findMany({
    where: {
      communityId: community.id,
      transactionType: { in: SALE_TXN_TYPES },
      pricePerSqft: { gt: 100 }, // excludes land and outlier records
      transactionDate: { gte: since },
    },
    select: { transactionDate: true, pricePerSqft: true, priceAed: true, source: true },
  })

  // Label the series by what is actually in the table. Hardcoding
  // "DLD · Dubai Pulse API" made the chart assert a government source no matter
  // what the rows were, including while the table held generated data.
  const present = new Set(transactions.map((t) => t.source))
  const sourceLabel =
    present.size === 0
      ? 'unknown'
      : present.has('dld') && present.has('adrec')
        ? 'DLD + ADREC'
        : present.has('dld')
          ? 'DLD (Dubai Pulse)'
          : present.has('adrec')
            ? 'ADREC (Abu Dhabi)'
            : [...present].join(', ')

  const monthMap = new Map<string, { psfs: number[]; volume: number; totalValue: number }>()
  for (const txn of transactions) {
    const key = txn.transactionDate.toISOString().substring(0, 7)
    const bucket = monthMap.get(key) ?? { psfs: [], volume: 0, totalValue: 0 }
    bucket.psfs.push(txn.pricePerSqft)
    bucket.volume++
    bucket.totalValue += txn.priceAed
    monthMap.set(key, bucket)
  }

  const trend = []
  for (let i = months; i >= 0; i--) {
    const d = new Date()
    d.setMonth(d.getMonth() - i)
    const key = d.toISOString().substring(0, 7)
    const bucket = monthMap.get(key)
    if (bucket && bucket.psfs.length > 0) {
      // True median (mean of the two central values on an even count). A plain
      // average would let one headline deal drag the whole month.
      const sorted = [...bucket.psfs].sort((a, b) => a - b)
      const mid = Math.floor(sorted.length / 2)
      const median = sorted.length % 2 === 0
        ? (sorted[mid - 1] + sorted[mid]) / 2
        : sorted[mid]
      trend.push({
        date: key,
        medianPrice: Math.round(median),
        volume: bucket.volume,
        totalValueAed: Math.round(bucket.totalValue),
        dataSource: sourceLabel,
        transactionCount: bucket.psfs.length,
      })
    } else {
      // null rather than 0 so the chart breaks the line instead of plotting a
      // cliff to the axis on months with no sales.
      trend.push({
        date: key, medianPrice: null, volume: 0,
        totalValueAed: 0, dataSource: sourceLabel, transactionCount: 0,
      })
    }
  }

  const hasRealData = trend.some((t) => t.medianPrice !== null)
  if (!hasRealData) {
    return c.json({
      trend: [],
      period,
      dataSource: 'no_transaction_data',
      message:
        'No registered transaction data for this area yet. Connect a source: set DUBAI_PULSE_API_KEY for Dubai, or ADREC_API_URL/ADREC_API_KEY for Abu Dhabi.',
      communityMedian: community.medianAedSqft,
    })
  }

  return c.json({ trend, period, dataSource: sourceLabel, sources: [...present] })
})

// ─── Yield Calculator ────────────────────────────────────────────────────────

app.post('/sqftlab/yield/calculate', async (c) => {
  const body = await c.req.json()
  const { purchasePrice, annualRent, serviceCharge, mortgageEnabled, mortgageRate, mortgageTerm, downPaymentPct } = body

  const grossYield = (annualRent / purchasePrice) * 100
  const dldFee = purchasePrice * 0.04
  const netYield = ((annualRent - serviceCharge - dldFee * 0.02) / purchasePrice) * 100
  const monthlyCashFlow = (annualRent - serviceCharge) / 12

  let emi = 0, totalMortgageCost = 0, totalInterest = 0
  if (mortgageEnabled && mortgageRate > 0) {
    const loanAmount = purchasePrice * (1 - downPaymentPct / 100)
    const monthlyRate = mortgageRate / 100 / 12
    const months = mortgageTerm * 12
    emi = loanAmount * monthlyRate * Math.pow(1 + monthlyRate, months) / (Math.pow(1 + monthlyRate, months) - 1)
    totalMortgageCost = emi * months
    totalInterest = totalMortgageCost - loanAmount
  }

  const breakEvenMonths = monthlyCashFlow > 0 ? Math.ceil((purchasePrice * 0.04) / monthlyCashFlow) : Infinity
  const annualCashFlow = annualRent - serviceCharge - emi * 12

  // 5-year projection (conservative: 0% price growth)
  const fiveYearReturn = (annualRent * 5 - serviceCharge * 5 - totalInterest) / purchasePrice * 100

  return c.json({
    grossYield: Math.round(grossYield * 100) / 100,
    netYield: Math.round(netYield * 100) / 100,
    monthlyCashFlow: Math.round(monthlyCashFlow),
    annualCashFlow: Math.round(annualCashFlow),
    emi: Math.round(emi),
    totalMortgageCost: Math.round(totalMortgageCost),
    totalInterest: Math.round(totalInterest),
    breakEvenMonths,
    fiveYearReturn: Math.round(fiveYearReturn * 100) / 100,
    dldFee: Math.round(dldFee),
  })
})

// ─── Mortgage Simulator ──────────────────────────────────────────────────────

app.post('/sqftlab/mortgage/simulate', async (c) => {
  const body = await c.req.json()
  const { price, downPaymentPct, ratePct, termYears } = body

  const downPayment = price * (downPaymentPct / 100)
  const loanAmount = price - downPayment
  const monthlyRate = ratePct / 100 / 12
  const months = termYears * 12
  const emi = loanAmount * monthlyRate * Math.pow(1 + monthlyRate, months) / (Math.pow(1 + monthlyRate, months) - 1)
  const totalPayment = emi * months
  const totalInterest = totalPayment - loanAmount

  // Amortization first 5 years
  const amortization = []
  let balance = loanAmount
  for (let year = 1; year <= Math.min(termYears, 5); year++) {
    let yearInterest = 0, yearPrincipal = 0
    for (let m = 0; m < 12; m++) {
      const interestPayment = balance * monthlyRate
      const principalPayment = emi - interestPayment
      yearInterest += interestPayment
      yearPrincipal += principalPayment
      balance -= principalPayment
    }
    amortization.push({
      year,
      principalPaid: Math.round(yearPrincipal),
      interestPaid: Math.round(yearInterest),
      remainingBalance: Math.round(Math.max(0, balance)),
    })
  }

  return c.json({
    emi: Math.round(emi),
    downPayment: Math.round(downPayment),
    loanAmount: Math.round(loanAmount),
    totalPayment: Math.round(totalPayment),
    totalInterest: Math.round(totalInterest),
    amortization,
    // These are NOT quotes from these banks. Each is a mechanical offset from the
    // rate the user typed in, so they must be labelled as illustrative — an
    // unlabelled list reads as a rate comparison sqftLab cannot stand behind.
    bankRates: [
      { bank: 'ADCB', rate: ratePct - 0.15, type: 'Variable' },
      { bank: 'Emirates NBD', rate: ratePct, type: 'Variable' },
      { bank: 'FAB', rate: ratePct - 0.10, type: 'Variable' },
      { bank: 'HSBC UAE', rate: ratePct + 0.05, type: 'Fixed 3yr' },
      { bank: 'Mashreq', rate: ratePct - 0.05, type: 'Variable' },
    ],
    bankRatesDisclaimer: 'Indicative rates only — calculated as offsets from your ' +
      'input rate. Verify actual rates with each bank before proceeding. ' +
      'sqftLab is not a mortgage broker.',
    disclaimer: 'This calculator provides illustrative calculations only. ' +
      'sqftLab does not provide mortgage advice. Rates shown are indicative. ' +
      'Contact a CBUAE-regulated bank or mortgage broker for actual rates.',
  })
})

// ─── Exchange Rates ──────────────────────────────────────────────────────────

// frankfurter (the previous source) does not publish INR or PKR at all, so both
// silently fell through to the hardcoded constants on every request — the UI
// showed a "live" rate that never changed. open.er-api.com covers all five
// currencies and needs no key.
const RATE_TTL_MS = 5 * 60 * 1000

app.get('/sqftlab/rates/exchange', async (c) => {
  // 1. Serve a cached row if it is younger than the TTL.
  const cached = await prisma.exchangeRate.findFirst({
    where: { base: 'AED', fetchedAt: { gte: new Date(Date.now() - RATE_TTL_MS) } },
    orderBy: { fetchedAt: 'desc' },
  })
  if (cached) {
    return c.json({
      AED_USD: cached.usd, AED_GBP: cached.gbp, AED_EUR: cached.eur,
      AED_INR: cached.inr, AED_PKR: cached.pkr,
      updatedAt: cached.fetchedAt, source: 'cache',
    })
  }

  // 2. Fetch live. Only a successful response is persisted, so a fallback value
  //    never gets stamped into the cache and replayed as "live" for 5 minutes.
  try {
    const res = await fetch('https://open.er-api.com/v6/latest/AED', {
      signal: AbortSignal.timeout(5000),
    })
    if (res.ok) {
      const data = await res.json()
      if (data?.result !== 'error') {
        const rates = {
          usd: data.rates?.USD ?? 0.2723,
          gbp: data.rates?.GBP ?? 0.2145,
          eur: data.rates?.EUR ?? 0.25,
          inr: data.rates?.INR ?? 22.68,
          pkr: data.rates?.PKR ?? 75.5,
        }
        await prisma.exchangeRate.create({ data: { base: 'AED', ...rates } })
        return c.json({
          AED_USD: rates.usd, AED_GBP: rates.gbp, AED_EUR: rates.eur,
          AED_INR: rates.inr, AED_PKR: rates.pkr,
          updatedAt: new Date().toISOString(), source: 'live',
        })
      }
    }
  } catch {}

  // 3. Clearly-labelled fallback.
  return c.json({
    AED_USD: 0.2723, AED_GBP: 0.2145, AED_EUR: 0.25,
    AED_INR: 22.68, AED_PKR: 75.5,
    updatedAt: new Date().toISOString(), source: 'fallback',
  })
})

// ─── Scraper: PropertyFinder ────────────────────────────────────────────────

// A static UA across a multi-minute crawl is a single reusable fingerprint.
const USER_AGENTS = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15',
]

const DUBAI_AREAS = [
  { name: 'Dubai Marina', lid: '31', slug: 'dubai-marina' },
  { name: 'Downtown Dubai', lid: '56', slug: 'downtown-dubai' },
  { name: 'Palm Jumeirah', lid: '63', slug: 'palm-jumeirah' },
  { name: 'JVC', lid: '544', slug: 'jumeirah-village-circle' },
  { name: 'Business Bay', lid: '53', slug: 'business-bay' },
  { name: 'Dubai Hills Estate', lid: '1436', slug: 'dubai-hills-estate' },
  { name: 'JLT', lid: '59', slug: 'jumeirah-lake-towers' },
  { name: 'DIFC', lid: '55', slug: 'difc' },
  { name: 'Dubai Creek Harbour', lid: '3476', slug: 'dubai-creek-harbour' },
  { name: 'MBR City', lid: '2424', slug: 'mbr-city' },
  { name: 'Al Barsha', lid: '40', slug: 'al-barsha' },
  { name: 'Deira', lid: '49', slug: 'deira' },
  { name: 'Bur Dubai', lid: '47', slug: 'bur-dubai' },
  { name: 'Dubai Silicon Oasis', lid: '109', slug: 'dubai-silicon-oasis' },
  { name: 'Dubai Sports City', lid: '103', slug: 'dubai-sports-city' },
  { name: 'Motor City', lid: '102', slug: 'motor-city' },
  { name: 'Discovery Gardens', lid: '58', slug: 'discovery-gardens' },
  { name: 'Town Square', lid: '2100', slug: 'town-square' },
  { name: 'Al Nahda', lid: '44', slug: 'al-nahda' },
  { name: 'Dubailand', lid: '105', slug: 'dubailand' },
]

const AD_AREAS = [
  { name: 'Al Reem Island', lid: '6665', slug: 'al-reem-island' },
  { name: 'Saadiyat Island', lid: '6666', slug: 'saadiyat-island' },
  { name: 'Yas Island', lid: '6667', slug: 'yas-island' },
  { name: 'Al Raha Beach', lid: '6668', slug: 'al-raha-beach' },
  { name: 'Corniche', lid: '6663', slug: 'corniche' },
  { name: 'Khalifa City', lid: '6670', slug: 'khalifa-city' },
  { name: 'MBZ City', lid: '6671', slug: 'mbz-city' },
  { name: 'Al Maryah Island', lid: '6669', slug: 'al-maryah-island' },
]

const sleepMs = (ms: number) => new Promise((r) => setTimeout(r, ms))

async function pfFetchPage(catId: number, locationId: string, page: number): Promise<any[]> {
  const url = `https://www.propertyfinder.ae/en/search?c=${catId}&l=${locationId}&ob=mr&page=${page}`
  try {
    const res = await fetch(url, {
      headers: {
        'User-Agent': USER_AGENTS[Math.floor(Math.random() * USER_AGENTS.length)],
        'Accept-Language': 'en-US,en;q=0.9',
      },
      signal: AbortSignal.timeout(15000),
    })
    if (!res.ok) return []
    const html = await res.text()
    const m = html.match(/<script id="__NEXT_DATA__"[^>]*>(.*?)<\/script>/)
    if (!m) return []
    const j = JSON.parse(m[1])
    const items = j?.props?.pageProps?.searchResult?.listings ?? []
    return items.filter((l: any) => l.listing_type === 'property' && l.property).map((l: any) => l.property)
  } catch { return [] }
}

function pfParse(property: any, source: string, purpose: string) {
  const price = property.price?.value ?? 0
  const area = property.size ?? 0
  const loc = property.location ?? {}
  return {
    externalId: `${source}_${property.id}`,
    source,
    purpose,
    propertyType: property.property_type ?? 'Apartment',
    beds: property.bedrooms_value ?? property.bedrooms ?? 0,
    baths: property.bathrooms_value ?? property.bathrooms ?? 0,
    areaSqft: area,
    priceAed: price,
    pricePerSqft: area > 0 ? Math.round(price / area) : 0,
    furnished: property.furnished === 'furnished' ? 'furnished' : 'unfurnished',
    completion: property.completion_status === 'off_plan' ? 'off_plan' : 'ready',
    agentName: property.agent?.name ?? null,
    agencyName: property.broker?.name ?? null,
    title: property.title ?? `${property.property_type} in ${loc.name ?? ''}`,
    imageUrl: property.images?.[0]?.medium ?? property.images?.[0]?.small ?? null,
    latitude: loc.coordinates?.lat ?? null,
    longitude: loc.coordinates?.lon ?? null,
    listedAt: new Date(property.listed_date ?? Date.now()),
    districtName: loc.name ?? 'Unknown',
    locationSlug: loc.slug ?? (loc.name ?? 'unknown').toLowerCase().replace(/\s+/g, '-'),
    sourceUrl: `https://www.propertyfinder.ae/en/property/${property.id ?? ''}.html`,
  }
}

async function ensureCommunity(name: string, slug: string, emirate: string) {
  let c = await prisma.community.findFirst({ where: { slug } })
  // Dialect-agnostic name lookup — Prisma's `mode: 'insensitive'` is
  // Postgres-only and throws on SQLite. See src/lib/community-match.ts.
  if (!c) c = await findCommunityByName(name)
  if (!c) {
    c = await prisma.community.create({
      data: {
        slug, nameEn: name, emirate, latitude: 25.2, longitude: 55.27,
        medianAedSqft: 0, medianAnnualRentAed: 0, grossYieldPct: 0,
        neighbourhoodScore: 50, priceChange30d: 0, priceChange1y: 0,
        transactionCount30d: 0, totalTransactions: 0,
      },
    })
    // The matcher caches the community list; a new row must not be invisible to
    // the next listing in this same scrape pass.
    invalidateCommunityCache()
  }
  return c
}

// Deal detection lives in src/lib/deals.ts so the scraper, the /detect-deals
// endpoint and the hourly cron share one implementation and cannot drift apart.
// It used to be defined here, which meant the cron would have needed a copy.

app.get('/sqftlab/scrape', async (c) => {
  const secret = c.req.query('secret')
  if (secret !== 'sqftlab-cron-2026') return c.json({ error: 'unauthorized' }, 401)

  const startedAt = Date.now()
  let totalSaved = 0
  const logs: string[] = []

  // Best-effort audit row. A missing/failing log table must never abort a scrape.
  const logRun = await prisma.scraperLog
    .create({ data: { source: 'propertyfinder', status: 'running', startedAt: new Date() } })
    .catch(() => null)

  // Circuit breaker. PropertyFinder returns an empty page both at the natural
  // end of a result set AND when it starts refusing us — so a run of empties
  // means we're being throttled. Left unchecked this crawls 22 areas × 2
  // categories × 3 pages against a host that is already saying no.
  let consecutiveFailures = 0
  let circuitBroken = false
  const MAX_FAILURES = 3

  // Scrape Dubai + Abu Dhabi
  for (const areas of [DUBAI_AREAS, AD_AREAS]) {
    const emirate = areas === DUBAI_AREAS ? 'dubai' : 'abu_dhabi'
    for (const area of areas) {
      for (const catId of [1, 2]) {
        const purpose = catId === 1 ? 'sale' : 'rent'
        for (let page = 1; page <= 3; page++) {
          const props = await pfFetchPage(catId, area.lid, page)
          if (props.length === 0) {
            consecutiveFailures++
            if (consecutiveFailures >= MAX_FAILURES) {
              circuitBroken = true
              logs.push(`Circuit breaker tripped: ${MAX_FAILURES} consecutive empty responses — stopping scrape`)
            }
            break // no further pages of this size
          }
          consecutiveFailures = 0
          for (const p of props) {
            try {
              const parsed = pfParse(p, 'propertyfinder', purpose)
              if (parsed.priceAed <= 0) continue
              const community = await ensureCommunity(parsed.districtName, parsed.locationSlug, emirate)
              await prisma.listing.upsert({
                where: { externalId: parsed.externalId },
                create: {
                  externalId: parsed.externalId, source: parsed.source,
                  communityId: community.id, purpose: parsed.purpose,
                  propertyType: parsed.propertyType, beds: parsed.beds,
                  baths: parsed.baths, areaSqft: parsed.areaSqft,
                  priceAed: parsed.priceAed, pricePerSqft: parsed.pricePerSqft,
                  furnished: parsed.furnished, completion: parsed.completion,
                  agentName: parsed.agentName, agencyName: parsed.agencyName,
                  title: parsed.title, imageUrl: parsed.imageUrl,
                  sourceUrl: parsed.sourceUrl,
                  latitude: parsed.latitude, longitude: parsed.longitude,
                  listedAt: parsed.listedAt, isDeal: false,
                },
                update: {
                  priceAed: parsed.priceAed, pricePerSqft: parsed.pricePerSqft,
                  title: parsed.title, imageUrl: parsed.imageUrl,
                  sourceUrl: parsed.sourceUrl,
                  agentName: parsed.agentName, agencyName: parsed.agencyName,
                  scrapedAt: new Date(),
                },
              })
              totalSaved++
            } catch {}
          }
          // Jittered 3–6s. The random component is the point: a fixed interval is
          // a trivially detectable pattern over a multi-minute crawl.
          await sleepMs(3000 + Math.random() * 3000)
        }
        if (circuitBroken) break
      }
      if (circuitBroken) break
    }
    if (circuitBroken) break
  }

  // Cleanup old listings (>30 days)
  const thirtyDaysAgo = new Date()
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30)
  const deleted = await prisma.listing.deleteMany({ where: { scrapedAt: { lt: thirtyDaysAgo } } })

  // ── Community stats: batched, and PSF sourced from DLD transactions ────────
  // This previously ran four queries per community inside a loop (4 × 39 round
  // trips) and derived PSF from listing asking prices — the opposite of what the
  // product claims. Now: five grouped queries total, and medianAedSqft prefers
  // the government register, recording which source won in `psfSource`.
  const [statsCommunities, listingPsfByComm, rentByComm, txCountByComm, txPsfByComm] = await Promise.all([
    prisma.community.findMany({
      select: { id: true, medianAedSqft: true, medianAnnualRentAed: true, grossYieldPct: true },
    }),
    prisma.listing.groupBy({
      by: ['communityId'],
      where: { purpose: 'sale', pricePerSqft: { gt: 0 } },
      _avg: { pricePerSqft: true },
    }),
    prisma.listing.groupBy({
      by: ['communityId'],
      where: { purpose: 'rent', priceAed: { gt: 0 } },
      _avg: { priceAed: true },
    }),
    prisma.transaction.groupBy({ by: ['communityId'], _count: { _all: true } }),
    prisma.transaction.groupBy({
      by: ['communityId'],
      where: { transactionType: { in: SALE_TXN_TYPES }, pricePerSqft: { gt: 100 } },
      _avg: { pricePerSqft: true },
    }),
  ])

  const listPsfMap = new Map(listingPsfByComm.map((r) => [r.communityId, r._avg.pricePerSqft ?? 0]))
  const rentMap = new Map(rentByComm.map((r) => [r.communityId, r._avg.priceAed ?? 0]))
  const txCountMap = new Map(txCountByComm.map((r) => [r.communityId, r._count._all]))
  const txPsfMap = new Map(txPsfByComm.map((r) => [r.communityId, r._avg.pricePerSqft ?? 0]))

  await prisma.$transaction(
    statsCommunities.map((comm) => {
      const txPsf = txPsfMap.get(comm.id) ?? 0
      const listPsf = listPsfMap.get(comm.id) ?? 0
      // A transaction-derived level is government-registered, so it wins over
      // asking prices whenever we actually have one.
      const mp = Math.round(txPsf > 0 ? txPsf : listPsf)
      const mr = Math.round(rentMap.get(comm.id) ?? 0)
      const yld = mp > 0 && mr > 0 ? Math.round((mr / (mp * 1000)) * 10000) / 100 : 0
      return prisma.community.update({
        where: { id: comm.id },
        data: {
          medianAedSqft: mp || comm.medianAedSqft,
          medianAnnualRentAed: mr || comm.medianAnnualRentAed,
          grossYieldPct: yld || comm.grossYieldPct,
          totalTransactions: txCountMap.get(comm.id) ?? 0,
          psfSource: txPsf > 0 ? 'dld' : 'listing',
        },
      })
    })
  )

  // ── Deal detection ────────────────────────────────────────────────────────
  const dealsDetected = await detectDeals()

  const elapsed = Math.round((Date.now() - startedAt) / 1000)
  const finalCount = await prisma.listing.count()

  if (logRun) {
    await prisma.scraperLog
      .update({
        where: { id: logRun.id },
        data: {
          status: circuitBroken ? 'partial' : 'success',
          recordsNew: totalSaved,
          finishedAt: new Date(),
          durationMs: Date.now() - startedAt,
        },
      })
      .catch(() => {})
  }

  return c.json({
    ok: true,
    saved: totalSaved,
    deleted: deleted.count,
    dealsDetected,
    totalListings: finalCount,
    communities: statsCommunities.length,
    circuitBroken,
    logs,
    elapsed: `${elapsed}s`,
  })
})

// ─── Scraper status ─────────────────────────────────────────────────────────

app.get('/sqftlab/scrape/status', async (c) => {
  const [listingCount, communityCount, transactionCount, oldestListing, newestListing] = await Promise.all([
    prisma.listing.count(),
    prisma.community.count(),
    prisma.transaction.count(),
    prisma.listing.findFirst({ orderBy: { scrapedAt: 'asc' }, select: { scrapedAt: true } }),
    prisma.listing.findFirst({ orderBy: { scrapedAt: 'desc' }, select: { scrapedAt: true } }),
  ])

  const byPurpose = await prisma.listing.groupBy({ by: ['purpose'], _count: true })
  const bySource = await prisma.listing.groupBy({ by: ['source'], _count: true })

  return c.json({
    listings: listingCount,
    communities: communityCount,
    transactions: transactionCount,
    oldestListing: oldestListing?.scrapedAt,
    newestListing: newestListing?.scrapedAt,
    byPurpose: Object.fromEntries(byPurpose.map(r => [r.purpose, r._count])),
    bySource: Object.fromEntries(bySource.map(r => [r.source, r._count])),
  })
})

// ─── Identity ────────────────────────────────────────────────────────────────

// Account-scoped routes resolve the caller from the request. This replaces the
// old hardcoded demo-user constant, which meant every visitor was served the
// same person's portfolio, watchlist and alerts regardless of who they were.
//
// NOTE: this is *identification*, not authentication. A bearer value or cookie
// is taken at face value, so it is not a security boundary — anyone can claim
// any user id. Its purpose is to stop account-scoped routes leaking a single
// global identity; real auth belongs in front of it.
function getUserId(c: Context): string | null {
  const auth = c.req.header('Authorization')
  if (auth?.startsWith('Bearer ')) return auth.slice(7).trim() || null
  const cookie = c.req.header('Cookie') ?? ''
  const match = cookie.match(/(?:^|;\s*)session=([^;]+)/)
  return match ? decodeURIComponent(match[1]) : null
}

function unauthorized(c: Context) {
  return c.json({ error: 'Unauthorized. Send `Authorization: Bearer <userId>` or a `session` cookie.' }, 401)
}

// The seeded demo account, resolved by email (falling back to the oldest user)
// so no cuid is baked into the source.
async function seededUserId(): Promise<string | null> {
  const user =
    (await prisma.user.findUnique({ where: { email: 'demo@sqftlab.ae' }, select: { id: true } })) ??
    (await prisma.user.findFirst({ orderBy: { createdAt: 'asc' }, select: { id: true } }))
  return user?.id ?? null
}

// ─── Portfolio ───────────────────────────────────────────────────────────────

app.get('/sqftlab/portfolio', async (c) => {
  const userId = getUserId(c)
  if (!userId) return unauthorized(c)

  const items = await prisma.portfolio.findMany({
    where: { userId },
    include: { community: { select: { nameEn: true, slug: true, medianAedSqft: true, grossYieldPct: true } } },
  })

  const totalValue = items.reduce((s, i) => s + i.currentValue, 0)
  const totalCost = items.reduce((s, i) => s + i.purchasePrice, 0)
  const totalGainLoss = totalValue - totalCost
  const totalAnnualRent = items.reduce((s, i) => s + i.annualRent, 0)
  const weightedYield = totalValue > 0 ? (totalAnnualRent / totalValue) * 100 : 0
  const monthlyCashFlow = items.reduce((s, i) => s + (i.annualRent - i.serviceCharge) / 12 - i.mortgageBalance * (i.mortgageRate / 100 / 12), 0)

  return c.json({
    items,
    summary: {
      totalValue: Math.round(totalValue),
      totalCost: Math.round(totalCost),
      totalGainLoss: Math.round(totalGainLoss),
      gainLossPct: Math.round((totalGainLoss / totalCost) * 10000) / 100,
      totalAnnualRent: Math.round(totalAnnualRent),
      weightedYield: Math.round(weightedYield * 100) / 100,
      monthlyCashFlow: Math.round(monthlyCashFlow),
      propertyCount: items.length,
    },
  })
})

// Add a holding. The spec showed `data: { userId, ...body }`, which spreads
// arbitrary client input straight into the row (mass assignment — a caller could
// set `purchaseDate` to any value, or `currentValue` to whatever they liked).
// Fields are validated instead.
app.post('/sqftlab/portfolio', async (c) => {
  const userId = getUserId(c)
  if (!userId) return unauthorized(c)

  let body: Record<string, unknown>
  try {
    body = await c.req.json()
  } catch {
    return c.json({ error: 'Request body must be JSON.' }, 400)
  }

  const communitySlug = typeof body.communitySlug === 'string' ? body.communitySlug.trim() : ''
  if (!communitySlug) return c.json({ error: 'communitySlug is required' }, 400)

  const community = await prisma.community.findUnique({
    where: { slug: communitySlug },
    select: { id: true },
  })
  if (!community) return c.json({ error: `Unknown district "${communitySlug}"` }, 400)

  const purchasePrice = Number(body.purchasePrice)
  if (!Number.isFinite(purchasePrice) || purchasePrice <= 0) {
    return c.json({ error: 'purchasePrice must be a positive number' }, 400)
  }
  const areaSqft = Number(body.areaSqft)
  if (!Number.isFinite(areaSqft) || areaSqft <= 0) {
    return c.json({ error: 'areaSqft must be a positive number' }, 400)
  }

  const num = (v: unknown, fallback = 0) => (Number.isFinite(Number(v)) ? Number(v) : fallback)
  const purchaseDate = body.purchaseDate ? new Date(String(body.purchaseDate)) : new Date()
  if (Number.isNaN(purchaseDate.getTime())) {
    return c.json({ error: 'purchaseDate must be a valid date' }, 400)
  }

  const item = await prisma.portfolio.create({
    data: {
      userId,
      communityId: community.id,
      title: typeof body.title === 'string' && body.title.trim() ? body.title.trim() : 'Untitled holding',
      propertyType:
        typeof body.propertyType === 'string' && body.propertyType.trim() ? body.propertyType.trim() : 'apartment',
      beds: Number.isInteger(Number(body.beds)) ? Number(body.beds) : 0,
      areaSqft,
      purchasePrice,
      purchaseDate,
      currentValue: num(body.currentValue, purchasePrice),
      annualRent: num(body.annualRent),
      serviceCharge: num(body.serviceCharge),
    },
  })

  return c.json({ item }, 201)
})

// ─── Watchlist ───────────────────────────────────────────────────────────────

app.get('/sqftlab/watchlist', async (c) => {
  const userId = getUserId(c)
  if (!userId) return unauthorized(c)

  const items = await prisma.watchlist.findMany({
    where: { userId },
    include: { community: true },
    orderBy: { addedAt: 'desc' },
  })
  return c.json({ items })
})

// ─── Deals ───────────────────────────────────────────────────────────────────

// Re-run deal detection without a full scrape. Same secret as /scrape so it can
// be driven from the cron without exposing a mutation to the public.
app.get('/sqftlab/detect-deals', async (c) => {
  const secret = c.req.query('secret')
  if (secret !== 'sqftlab-cron-2026') return c.json({ error: 'unauthorized' }, 401)

  const dealsDetected = await detectDeals()
  return c.json({ ok: true, dealsDetected })
})

app.get('/sqftlab/deals', async (c) => {
  const deals = await prisma.listing.findMany({
    where: { isDeal: true, purpose: 'sale' },
    include: { community: { select: { nameEn: true, slug: true, medianAedSqft: true } } },
    orderBy: { listedAt: 'desc' },
    take: 30,
  })

  // How far below the district median each listing sits. Without this the UI can
  // only show a "deal" badge with no magnitude behind it.
  const dealsWithDiscount = deals.map((d) => ({
    ...d,
    discountPct:
      d.community.medianAedSqft > 0 && d.pricePerSqft > 0
        ? Math.round((1 - d.pricePerSqft / d.community.medianAedSqft) * 100 * 10) / 10
        : 0,
  }))

  return c.json({ deals: dealsWithDiscount })
})

// ─── Listings search ─────────────────────────────────────────────────────────

app.get('/sqftlab/listings', async (c) => {
  const purpose = c.req.query('purpose') || 'sale'
  const emirate = c.req.query('emirate')
  const beds = c.req.query('beds')
  const propertyType = c.req.query('type')
  const dealsOnly = c.req.query('deals') === 'true'
  const priceMin = c.req.query('priceMin')
  const priceMax = c.req.query('priceMax')
  const page = parseInt(c.req.query('page') || '1')
  const limit = 20

  const where: Record<string, unknown> = { purpose }
  if (dealsOnly) where.isDeal = true
  if (beds) where.beds = parseInt(beds)
  if (propertyType) where.propertyType = propertyType
  if (priceMin || priceMax) {
    where.priceAed = {}
    if (priceMin) (where.priceAed as Record<string, number>).gte = parseInt(priceMin)
    if (priceMax) (where.priceAed as Record<string, number>).lte = parseInt(priceMax)
  }
  if (emirate && emirate !== 'all') {
    where.community = { emirate }
  }

  const [listings, total] = await Promise.all([
    prisma.listing.findMany({
      where,
      include: { community: { select: { nameEn: true, slug: true, emirate: true, medianAedSqft: true } } },
      orderBy: { listedAt: 'desc' },
      skip: (page - 1) * limit,
      take: limit,
    }),
    prisma.listing.count({ where }),
  ])

  return c.json({ listings, total, page, pages: Math.ceil(total / limit) })
})

// ─── Alerts ──────────────────────────────────────────────────────────────────

// Legacy rule-based alerts (Alert model). The Deal Alert Engine (TASK 12) owns
// /sqftlab/alerts, so these stay reachable at their own path rather than
// shadowing the new CRUD routes.
app.get('/sqftlab/alert-rules', async (c) => {
  const userId = getUserId(c)
  if (!userId) return unauthorized(c)

  const alerts = await prisma.alert.findMany({
    where: { userId },
    include: { community: { select: { nameEn: true, slug: true } } },
    orderBy: { createdAt: 'desc' },
  })
  return c.json({ alerts })
})

// ─── Market Analytics ────────────────────────────────────────────────────────

app.get('/sqftlab/market/analytics', async (c) => {
  const [communities, transactions, listings] = await Promise.all([
    prisma.community.findMany({
      orderBy: { medianAedSqft: 'desc' },
      select: {
        id: true, nameEn: true, slug: true, emirate: true,
        medianAedSqft: true, medianAnnualRentAed: true, grossYieldPct: true,
        priceChange30d: true, priceChange1y: true, transactionCount30d: true,
        totalTransactions: true,
      },
    }),
    prisma.transaction.groupBy({
      by: ['transactionType'],
      _count: true,
      _avg: { priceAed: true, pricePerSqft: true },
    }),
    prisma.listing.groupBy({
      by: ['purpose', 'propertyType'],
      _count: true,
      _avg: { priceAed: true, pricePerSqft: true },
    }),
  ])

  const totalTransactions = communities.reduce((s, c) => s + c.totalTransactions, 0)
  const totalTx30d = communities.reduce((s, c) => s + c.transactionCount30d, 0)
  const avgPsf = Math.round(communities.reduce((s, c) => s + c.medianAedSqft, 0) / communities.length)
  const avgYield = Math.round(communities.reduce((s, c) => s + c.grossYieldPct, 0) / communities.length * 100) / 100
  const avgPriceChange30d = Math.round(communities.reduce((s, c) => s + c.priceChange30d, 0) / communities.length * 100) / 100
  const avgPriceChange1y = Math.round(communities.reduce((s, c) => s + c.priceChange1y, 0) / communities.length * 100) / 100

  const topGainers = [...communities].sort((a, b) => b.priceChange30d - a.priceChange30d).slice(0, 10)
  const topLosers = [...communities].sort((a, b) => a.priceChange30d - b.priceChange30d).slice(0, 10)
  const highestYield = [...communities].sort((a, b) => b.grossYieldPct - a.grossYieldPct).slice(0, 10)
  const mostActive = [...communities].sort((a, b) => b.transactionCount30d - a.transactionCount30d).slice(0, 10)

  const priceBuckets = [
    { label: '< AED 1K', min: 0, max: 1000, count: 0 },
    { label: 'AED 1K-1.5K', min: 1000, max: 1500, count: 0 },
    { label: 'AED 1.5K-2K', min: 1500, max: 2000, count: 0 },
    { label: 'AED 2K-3K', min: 2000, max: 3000, count: 0 },
    { label: 'AED 3K-5K', min: 3000, max: 5000, count: 0 },
    { label: 'AED 5K+', min: 5000, max: Infinity, count: 0 },
  ]
  communities.forEach(c => {
    const bucket = priceBuckets.find(b => c.medianAedSqft >= b.min && c.medianAedSqft < b.max)
    if (bucket) bucket.count++
  })

  return c.json({
    summary: {
      communities: communities.length,
      totalTransactions,
      totalTx30d,
      totalListings: listings.reduce((s, l) => s + l._count, 0),
      avgPsf,
      avgYield,
      avgPriceChange30d,
      avgPriceChange1y,
    },
    topGainers,
    topLosers,
    highestYield,
    mostActive,
    priceBuckets,
    transactionTypes: transactions.map(t => ({
      type: t.transactionType,
      count: t._count,
      avgPrice: Math.round(t._avg.priceAed ?? 0),
      avgPsf: Math.round(t._avg.pricePerSqft ?? 0),
    })),
    listingsByType: listings.map(l => ({
      purpose: l.purpose,
      propertyType: l.propertyType,
      count: l._count,
      avgPrice: Math.round(l._avg.priceAed ?? 0),
    })),
  })
})

// ─── Price Predictions ──────────────────────────────────────────────────────

app.get('/sqftlab/predictions', async (c) => {
  const communities = await prisma.community.findMany({
    orderBy: { medianAedSqft: 'desc' },
    select: {
      id: true, nameEn: true, slug: true, emirate: true,
      medianAedSqft: true, medianAnnualRentAed: true, grossYieldPct: true,
      priceChange30d: true, priceChange1y: true, transactionCount30d: true,
      totalTransactions: true, neighbourhoodScore: true,
    },
  })

  const predictions = communities.map(c => {
    const momentum = c.priceChange30d * 12
    const historicalGrowth = c.priceChange1y
    const yieldSignal = c.grossYieldPct > 7 ? 1 : c.grossYieldPct > 5 ? 0 : -1
    const volumeSignal = c.transactionCount30d > 100 ? 1 : c.transactionCount30d > 50 ? 0 : -1
    const scoreSignal = c.neighbourhoodScore > 70 ? 1 : c.neighbourhoodScore > 50 ? 0 : -1

    const rawScore = momentum * 0.3 + historicalGrowth * 0.4 + yieldSignal * 5 + volumeSignal * 3 + scoreSignal * 2
    const confidence = Math.min(95, Math.max(45, 60 + c.transactionCount30d * 0.1 + (c.totalTransactions > 100 ? 10 : 0)))

    const forecast6m = Math.round(c.medianAedSqft * (1 + (rawScore / 100) * 0.5) * 100) / 100
    const forecast12m = Math.round(c.medianAedSqft * (1 + (rawScore / 100) * 1.0) * 100) / 100
    // Named `projectedChange*` so the identifier itself says these are
    // extrapolations, not promises. The old "Strong Buy / Buy / Hold / Sell /
    // Avoid" labels are gone: they read as licensed investment advice while
    // being derived from a five-line arithmetic formula.
    const projectedChange6m = Math.round((forecast6m / c.medianAedSqft - 1) * 10000) / 100
    const projectedChange12m = Math.round((forecast12m / c.medianAedSqft - 1) * 10000) / 100

    const momentumLabel =
      projectedChange6m > 5 ? 'Strong upward trend'
      : projectedChange6m > 2 ? 'Moderate upward trend'
      : projectedChange6m > -2 ? 'Stable'
      : projectedChange6m > -5 ? 'Moderate downward trend'
      : 'Declining trend'

    const riskLevel = confidence > 75 ? 'Low' : confidence > 60 ? 'Medium' : 'High'

    return {
      community: c.nameEn,
      slug: c.slug,
      emirate: c.emirate,
      currentPsf: c.medianAedSqft,
      forecast6m,
      forecast12m,
      projectedChange6m,
      projectedChange12m,
      momentumLabel,
      confidence: Math.round(confidence),
      riskLevel,
      momentum: Math.round(momentum * 100) / 100,
      yield: c.grossYieldPct,
      volume: c.transactionCount30d,
      score: c.neighbourhoodScore,
    }
  })

  // Momentum buckets replace the buy/sell buckets: they describe the trend
  // rather than advising an action, and the response carries a disclaimer.
  const rising = predictions.filter(p => p.projectedChange6m > 2).length
  const stable = predictions.filter(p => p.projectedChange6m <= 2 && p.projectedChange6m >= -2).length
  const falling = predictions.filter(p => p.projectedChange6m < -2).length

  return c.json({
    disclaimer: 'Projections are based on historical trend extrapolation only. ' +
      'Not financial advice. Past performance does not predict future results. ' +
      'Consult a RERA-licensed agent before transacting.',
    predictions,
    summary: {
      rising,
      stable,
      falling,
      totalAnalyzed: predictions.length,
    },
    topMomentum: [...predictions].sort((a, b) => b.projectedChange6m - a.projectedChange6m).slice(0, 5),
    topGrowth: [...predictions].sort((a, b) => b.projectedChange12m - a.projectedChange12m).slice(0, 5),
    topYield: [...predictions].sort((a, b) => b.yield - a.yield).slice(0, 5),
  })
})

// ─── Transaction Analytics ──────────────────────────────────────────────────

app.get('/sqftlab/market/transactions', async (c) => {
  const communities = await prisma.community.findMany({
    select: { id: true, nameEn: true, slug: true },
  })

  const transactionsByType = await prisma.transaction.groupBy({
    by: ['transactionType'],
    _count: true,
    _avg: { priceAed: true, pricePerSqft: true },
    _sum: { priceAed: true },
  })

  const transactionsByProperty = await prisma.transaction.groupBy({
    by: ['propertyType'],
    _count: true,
    _avg: { priceAed: true, pricePerSqft: true },
  })

  const transactionsByBeds = await prisma.transaction.groupBy({
    by: ['beds'],
    _count: true,
    _avg: { priceAed: true, pricePerSqft: true },
    orderBy: { beds: 'asc' },
  })

  const recentTransactions = await prisma.transaction.findMany({
    orderBy: { transactionDate: 'desc' },
    take: 50,
    include: { community: { select: { nameEn: true, slug: true } } },
  })

  const priceRanges = [
    { label: '< AED 500K', min: 0, max: 500000, count: 0, totalValue: 0 },
    { label: 'AED 500K-1M', min: 500000, max: 1000000, count: 0, totalValue: 0 },
    { label: 'AED 1M-2M', min: 1000000, max: 2000000, count: 0, totalValue: 0 },
    { label: 'AED 2M-5M', min: 2000000, max: 5000000, count: 0, totalValue: 0 },
    { label: 'AED 5M-10M', min: 5000000, max: 10000000, count: 0, totalValue: 0 },
    { label: 'AED 10M+', min: 10000000, max: Infinity, count: 0, totalValue: 0 },
  ]

  recentTransactions.forEach(t => {
    const bucket = priceRanges.find(r => t.priceAed >= r.min && t.priceAed < r.max)
    if (bucket) {
      bucket.count++
      bucket.totalValue += t.priceAed
    }
  })

  return c.json({
    summary: {
      totalTransactions: recentTransactions.length,
      totalValue: priceRanges.reduce((s, r) => s + r.totalValue, 0),
      avgPrice: Math.round(recentTransactions.reduce((s, t) => s + t.priceAed, 0) / recentTransactions.length),
      avgPsf: Math.round(recentTransactions.reduce((s, t) => s + t.pricePerSqft, 0) / recentTransactions.length),
    },
    byType: transactionsByType.map(t => ({
      type: t.transactionType,
      count: t._count,
      avgPrice: Math.round(t._avg.priceAed ?? 0),
      avgPsf: Math.round(t._avg.pricePerSqft ?? 0),
      totalValue: Number(t._sum.priceAed ?? 0),
    })),
    byProperty: transactionsByProperty.map(t => ({
      type: t.propertyType,
      count: t._count,
      avgPrice: Math.round(t._avg.priceAed ?? 0),
      avgPsf: Math.round(t._avg.pricePerSqft ?? 0),
    })),
    byBeds: transactionsByBeds.map(t => ({
      beds: t.beds,
      count: t._count,
      avgPrice: Math.round(t._avg.priceAed ?? 0),
      avgPsf: Math.round(t._avg.pricePerSqft ?? 0),
    })),
    priceRanges,
    recent: recentTransactions.slice(0, 20),
  })
})

// ─── Stats for dashboard ─────────────────────────────────────────────────────

app.get('/sqftlab/stats', async (c) => {
  const [communityCount, transactionCount, listingCount, dealCount] = await Promise.all([
    prisma.community.count(),
    prisma.transaction.count(),
    prisma.listing.count(),
    prisma.listing.count({ where: { isDeal: true } }),
  ])

  const topCommunities = await prisma.community.findMany({
    orderBy: { priceChange30d: 'desc' },
    take: 5,
    select: { nameEn: true, slug: true, priceChange30d: true, medianAedSqft: true },
  })

  return c.json({ communityCount, transactionCount, listingCount, dealCount, topCommunities })
})

// ─── Pro Tier Intelligence (spec Part 8.3) ───────────────────────────────────

const UAE_CPI_YOY = [3.1, 3.4, 3.2, 2.9, 2.7, 2.8, 3.0, 3.3, 3.5, 3.2, 2.9, 2.6]
const UAE_GDP_GROWTH = 3.9
const AED_PER_USD = 3.6725

app.get('/sqftlab/intelligence', async (c) => {
  const [communities, txns, listingGroups] = await Promise.all([
    prisma.community.findMany({ orderBy: { medianAedSqft: 'desc' } }),
    prisma.transaction.findMany({
      select: {
        communityId: true,
        priceAed: true,
        pricePerSqft: true,
        transactionType: true,
        transactionDate: true,
      },
    }),
    prisma.listing.groupBy({ by: ['purpose'], _count: { _all: true } }),
  ])

  const byId = new Map(communities.map((x) => [x.id, x]))
  const buckets = new Map<string, Map<string, { sum: number; n: number }>>()
  const valueByCommunity = new Map<string, number>()
  const typeBuckets = new Map<string, { volume: number; count: number }>()

  for (const t of txns) {
    const month = t.transactionDate.toISOString().substring(0, 7)
    const m = buckets.get(month) ?? new Map<string, { sum: number; n: number }>()
    const cell = m.get(t.communityId) ?? { sum: 0, n: 0 }
    cell.sum += t.pricePerSqft
    cell.n += 1
    m.set(t.communityId, cell)
    buckets.set(month, m)

    valueByCommunity.set(t.communityId, (valueByCommunity.get(t.communityId) ?? 0) + t.priceAed)

    const tb = typeBuckets.get(t.transactionType) ?? { volume: 0, count: 0 }
    tb.volume += t.priceAed
    tb.count += 1
    typeBuckets.set(t.transactionType, tb)
  }

  const months = [...buckets.keys()].sort()
  const seriesDistricts = communities.slice(0, 6)
  const series = months.map((month) => {
    const row: Record<string, number | string> = { month }
    for (const d of seriesDistricts) {
      const cell = buckets.get(month)?.get(d.id)
      row[d.slug] = cell && cell.n > 0 ? Math.round(cell.sum / cell.n) : 0
    }
    return row
  })

  const totalValue = [...valueByCommunity.values()].reduce((a, b) => a + b, 0)
  const avgPsf = communities.length
    ? Math.round(communities.reduce((a, d) => a + d.medianAedSqft, 0) / communities.length)
    : 0
  const avgYield = communities.length
    ? communities.reduce((a, d) => a + d.grossYieldPct, 0) / communities.length
    : 0
  const avgMomentum = communities.length
    ? communities.reduce((a, d) => a + d.priceChange30d, 0) / communities.length
    : 0
  const activeListings = listingGroups.reduce((a, g) => a + g._count._all, 0)

  const gainers = [...communities].sort((a, b) => b.priceChange30d - a.priceChange30d)
  const losers = [...communities].sort((a, b) => a.priceChange30d - b.priceChange30d)
  const breadth = {
    gainers: communities.filter((d) => d.priceChange30d > 0.5).length,
    flat: communities.filter((d) => d.priceChange30d >= -0.5 && d.priceChange30d <= 0.5).length,
    losers: communities.filter((d) => d.priceChange30d < -0.5).length,
  }

  const scatter = communities.map((d) => ({
    slug: d.slug,
    name: d.nameEn,
    psf: d.medianAedSqft,
    yield: d.grossYieldPct,
    volume: d.transactionCount30d,
    momentum: d.priceChange30d,
  }))

  const flow = [...valueByCommunity.entries()]
    .map(([id, value]) => {
      const d = byId.get(id)
      if (!d) return null
      const perTxn = value / Math.max(1, d.transactionCount30d || 1)
      return {
        slug: d.slug,
        name: d.nameEn,
        valueAed: Math.round(value),
        perTxnAed: Math.round(perTxn),
        txnCount: d.transactionCount30d,
        direction: d.priceChange30d >= 0 ? 'inflow' : 'outflow',
      }
    })
    .filter((x): x is NonNullable<typeof x> => x !== null)
    .sort((a, b) => b.valueAed - a.valueAed)

  const flowTotal = flow.reduce((a, d) => a + d.valueAed, 0)
  const topFlowCut = flow.slice(0, 8).reduce((a, d) => a + d.valueAed, 0)

  return c.json({
    overview: {
      avgPsf,
      avgYield: Number(avgYield.toFixed(2)),
      momentumIndex: Number(avgMomentum.toFixed(2)),
      transactionCount: txns.length,
      totalValueAed: Math.round(totalValue),
      activeListings,
      districtsTracked: communities.length,
      breadth,
    },
    gainers: gainers.slice(0, 5).map((d) => ({
      slug: d.slug, name: d.nameEn, change: d.priceChange30d, psf: d.medianAedSqft,
    })),
    losers: losers.slice(0, 5).map((d) => ({
      slug: d.slug, name: d.nameEn, change: d.priceChange30d, psf: d.medianAedSqft,
    })),
    seriesDistricts: seriesDistricts.map((d) => ({ slug: d.slug, name: d.nameEn })),
    series,
    scatter,
    scatterMedian: {
      psf: scatter.length
        ? Math.round(scatter.map((s) => s.psf).sort((a, b) => a - b)[Math.floor(scatter.length / 2)])
        : 0,
      yield: scatter.length
        ? Number(scatter.map((s) => s.yield).sort((a, b) => a - b)[Math.floor(scatter.length / 2)].toFixed(2))
        : 0,
    },
    flow: flow.slice(0, 10),
    flowSummary: {
      totalValueAed: flowTotal,
      topDistrictsSharePct: flowTotal ? Math.round((topFlowCut / flowTotal) * 1000) / 10 : 0,
      inflow: flow.filter((f) => f.direction === 'inflow').length,
      outflow: flow.filter((f) => f.direction === 'outflow').length,
    },
    transactionTypes: [...typeBuckets.entries()].map(([type, v]) => ({
      type, volumeAed: Math.round(v.volume), count: v.count,
    })),
    economic: {
      cpiYoyPct: UAE_CPI_YOY[new Date().getUTCMonth()],
      cpiSeries: months.map((m, i) => ({ month: m, cpi: UAE_CPI_YOY[i % UAE_CPI_YOY.length] })),
      gdpGrowthPct: UAE_GDP_GROWTH,
      aedPerUsd: AED_PER_USD,
      fxNote: 'AED is pegged to USD at 3.6725 — FX moves are a US-dollar story, not a dirham story.',
    },
    computedAt: new Date().toISOString(),
  })
})

// ─── Waitlist (spec Part 8.9) ────────────────────────────────────────────────

app.post('/sqftlab/waitlist', async (c) => {
  let body: { email?: string; tier?: string; source?: string }
  try {
    body = await c.req.json()
  } catch {
    return c.json({ error: 'Invalid JSON body' }, 400)
  }

  const email = (body.email ?? '').trim().toLowerCase()
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) {
    return c.json({ error: 'Please enter a valid email address.' }, 400)
  }

  const tier = body.tier === 'elite' ? 'elite' : 'pro'
  const source = (body.source ?? 'waitlist_page').slice(0, 60)

  const existing = await prisma.waitlist.findUnique({ where: { email } })
  if (existing) {
    const count = await prisma.waitlist.count()
    return c.json({ ok: true, alreadyRegistered: true, position: count, email })
  }

  await prisma.waitlist.create({ data: { email, interestTier: tier, source } })
  const count = await prisma.waitlist.count()
  return c.json({ ok: true, alreadyRegistered: false, position: count, email })
})

app.get('/sqftlab/waitlist', async (c) => {
  const count = await prisma.waitlist.count()
  return c.json({ count })
})

// ─── TASK 8 — District market table ──────────────────────────────────────────
// One row per district with the spec's columns. Every value is aggregated from
// the register — nothing is synthesized, so a district with thin data reports
// null for a change rather than inventing a number.
app.get('/sqftlab/markets', async (c) => {
  const emirate = c.req.query('emirate')
  const propertyType = c.req.query('type')

  const communityWhere: Record<string, unknown> = {}
  if (emirate && emirate !== 'all') communityWhere.emirate = emirate

  const communities = await prisma.community.findMany({
    where: communityWhere,
    select: {
      id: true, slug: true, nameEn: true, emirate: true,
      medianAedSqft: true, grossYieldPct: true, priceChange30d: true,
      priceChange1y: true, transactionCount30d: true, totalTransactions: true,
      medianAnnualRentAed: true,
    },
  })

  // Sale listings per district, respecting the property-type filter.
  const listingWhere: Record<string, unknown> = { purpose: 'sale' }
  if (propertyType && propertyType !== 'any') listingWhere.propertyType = propertyType
  const listingGroups = await prisma.listing.groupBy({
    by: ['communityId'],
    where: listingWhere,
    _count: { _all: true },
  })
  const listingsByCommunity = new Map(listingGroups.map((g) => [g.communityId, g._count._all]))

  // 3-month change: mean realised PSF over the last 3 months vs the 3 before it.
  const sixMonthsAgo = new Date()
  sixMonthsAgo.setUTCMonth(sixMonthsAgo.getUTCMonth() - 6)
  const threeMonthsAgo = new Date()
  threeMonthsAgo.setUTCMonth(threeMonthsAgo.getUTCMonth() - 3)

  const txns = await prisma.transaction.findMany({
    where: { transactionDate: { gte: sixMonthsAgo }, pricePerSqft: { gt: 0 } },
    select: { communityId: true, transactionDate: true, pricePerSqft: true },
  })

  const recent = new Map<string, number[]>()
  const prior = new Map<string, number[]>()
  for (const t of txns) {
    const target = t.transactionDate >= threeMonthsAgo ? recent : prior
    const list = target.get(t.communityId)
    if (list) list.push(t.pricePerSqft)
    else target.set(t.communityId, [t.pricePerSqft])
  }
  const mean = (a?: number[]) => (a && a.length ? a.reduce((s, v) => s + v, 0) / a.length : null)

  const rows = communities.map((k) => {
    const recentMean = mean(recent.get(k.id))
    const priorMean = mean(prior.get(k.id))
    const change3m =
      recentMean != null && priorMean != null && priorMean > 0
        ? ((recentMean - priorMean) / priorMean) * 100
        : null

    // Momentum blends 30-day price movement with yield — a district that is both
    // appreciating and yielding well scores high.
    const momentum = (k.priceChange30d ?? 0) + (k.grossYieldPct ?? 0) * 0.5

    return {
      slug: k.slug,
      nameEn: k.nameEn,
      emirate: k.emirate,
      avgPsf: Math.round(k.medianAedSqft),
      change3m: change3m != null ? Number(change3m.toFixed(2)) : null,
      change12m: Number((k.priceChange1y ?? 0).toFixed(2)),
      volume: k.totalTransactions,
      volume30d: k.transactionCount30d,
      listings: listingsByCommunity.get(k.id) ?? 0,
      momentum: Number(momentum.toFixed(2)),
      grossYieldPct: k.grossYieldPct ?? 0,
      medianAnnualRentAed: k.medianAnnualRentAed ?? 0,
    }
  })

  return c.json({
    rows,
    count: rows.length,
    totals: {
      volume: rows.reduce((s, r) => s + r.volume, 0),
      listings: rows.reduce((s, r) => s + r.listings, 0),
    },
  })
})

// ─── TASK 10 — Price trend forecasting ───────────────────────────────────────
// Least-squares linear regression over the last 12 months of realised PSF, per
// the spec formula:
//   slope     = (n·Σxy − Σx·Σy) / (n·Σx² − (Σx)²)
//   intercept = (Σy − slope·Σx) / n
// Confidence is R² combined with a residual-based band that widens with horizon.
app.get('/sqftlab/forecast', async (c) => {
  const district = c.req.query('district')
  const months = Math.min(Math.max(parseInt(c.req.query('months') || '6'), 1), 24)

  if (!district) return c.json({ error: 'district is required' }, 400)

  const community = await prisma.community.findFirst({
    where: { OR: [{ slug: district }, { nameEn: district }] },
    select: { id: true, nameEn: true, slug: true, medianAedSqft: true },
  })
  if (!community) return c.json({ error: `Unknown district "${district}"` }, 404)

  const since = new Date()
  since.setUTCMonth(since.getUTCMonth() - 11)
  since.setUTCDate(1)
  since.setUTCHours(0, 0, 0, 0)

  const txns = await prisma.transaction.findMany({
    where: {
      communityId: community.id,
      transactionDate: { gte: since },
      pricePerSqft: { gt: 0 },
    },
    select: { transactionDate: true, pricePerSqft: true },
  })

  const buckets = new Map<string, number[]>()
  for (const t of txns) {
    const d = t.transactionDate
    const key = `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`
    const list = buckets.get(key)
    if (list) list.push(t.pricePerSqft)
    else buckets.set(key, [t.pricePerSqft])
  }

  const history = [...buckets.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([month, prices]) => ({
      date: `${month}-01`,
      psf: prices.reduce((s, p) => s + p, 0) / prices.length,
      sampleSize: prices.length,
    }))

  if (history.length < 3) {
    return c.json({
      district: community.nameEn,
      slug: community.slug,
      history,
      forecast: [],
      regression: null,
      note: 'Not enough monthly history to fit a trend (need at least 3 months).',
    })
  }

  const n = history.length
  const xs = history.map((_, i) => i)
  const ys = history.map((h) => h.psf)
  const sumX = xs.reduce((s, x) => s + x, 0)
  const sumY = ys.reduce((s, y) => s + y, 0)
  const sumXY = xs.reduce((s, x, i) => s + x * ys[i], 0)
  const sumXX = xs.reduce((s, x) => s + x * x, 0)

  const denominator = n * sumXX - sumX * sumX
  const slope = denominator === 0 ? 0 : (n * sumXY - sumX * sumY) / denominator
  const intercept = (sumY - slope * sumX) / n

  // R² — how much of the variance the trend line explains.
  const meanY = sumY / n
  const ssTot = ys.reduce((s, y) => s + (y - meanY) ** 2, 0)
  const ssRes = ys.reduce((s, y, i) => s + (y - (intercept + slope * i)) ** 2, 0)
  const r2 = ssTot === 0 ? 0 : Math.max(0, 1 - ssRes / ssTot)
  const residualStd = Math.sqrt(ssRes / Math.max(1, n - 2))

  const lastDate = new Date(history[n - 1].date)
  const forecast = Array.from({ length: months }, (_, k) => {
    const x = n + k
    const psf = intercept + slope * x
    const horizon = k + 1
    // Band widens with the horizon — a 6-month projection is less certain than
    // a 1-month one by sqrt(horizon).
    const band = 1.96 * residualStd * Math.sqrt(1 + horizon / n)
    const d = new Date(lastDate)
    d.setUTCMonth(d.getUTCMonth() + horizon)
    // Confidence decays with horizon but never claims certainty.
    const confidence = Math.round(Math.max(35, Math.min(95, r2 * 100 - horizon * 2.5 + 20)))
    return {
      date: d.toISOString().slice(0, 10),
      psf: Math.max(0, psf),
      lower: Math.max(0, psf - band),
      upper: psf + band,
      confidence,
    }
  })

  return c.json({
    district: community.nameEn,
    slug: community.slug,
    currentPsf: community.medianAedSqft,
    history,
    forecast,
    regression: {
      slope,
      intercept,
      r2,
      residualStd,
      monthsOfHistory: n,
      direction: slope > 0 ? 'rising' : slope < 0 ? 'falling' : 'flat',
      monthlyChangePct: meanY > 0 ? (slope / meanY) * 100 : 0,
    },
  })
})

// ─── TASK 12 — Deal alert CRUD + engine ──────────────────────────────────────

// Identity bootstrap. `/me` answers "who is this?", so it deliberately does NOT
// require a session — if it did, the client could never learn its own id. With
// no session it resolves the seeded account (the pre-auth placeholder), which
// keeps tier gating and the account-scoped pages working.
app.get('/sqftlab/me', async (c) => {
  const userId = getUserId(c) ?? (await seededUserId())
  if (!userId) return c.json({ error: 'No user account configured' }, 404)

  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, email: true, name: true, tier: true, subscriptionStatus: true },
  })
  if (!user) return c.json({ error: 'No user account configured' }, 404)
  return c.json({ user })
})

// GET /sqftlab/alerts — active alerts plus the recent matches they produced.
app.get('/sqftlab/alerts', async (c) => {
  const userId = getUserId(c)
  if (!userId) return unauthorized(c)

  const alerts = await prisma.dealAlert.findMany({
    where: { userId },
    orderBy: { createdAt: 'desc' },
    include: { _count: { select: { matches: true } } },
  })
  return c.json({ alerts })
})

app.get('/sqftlab/alerts/matches', async (c) => {
  const userId = getUserId(c)
  if (!userId) return unauthorized(c)

  const matches = await recentMatches(userId)
  return c.json({ matches })
})

// POST /sqftlab/alerts — create a watch. Validated, because an alert with a
// bogus district silently never fires and looks like a broken engine.
app.post('/sqftlab/alerts', async (c) => {
  const userId = getUserId(c)
  if (!userId) return unauthorized(c)

  let body: Record<string, unknown>
  try {
    body = await c.req.json()
  } catch {
    return c.json({ error: 'Request body must be JSON.' }, 400)
  }

  const district = typeof body.district === 'string' ? body.district.trim() : ''
  if (!district) return c.json({ error: 'district is required' }, 400)

  const community = await prisma.community.findFirst({
    where: { OR: [{ slug: district }, { nameEn: district }] },
    select: { slug: true },
  })
  if (!community) return c.json({ error: `Unknown district "${district}"` }, 400)

  const propertyType =
    typeof body.propertyType === 'string' && body.propertyType && body.propertyType !== 'any'
      ? body.propertyType
      : null
  const maxPrice = body.maxPrice != null && body.maxPrice !== '' ? Number(body.maxPrice) : null
  if (maxPrice != null && (!Number.isFinite(maxPrice) || maxPrice <= 0)) {
    return c.json({ error: 'maxPrice must be a positive number' }, 400)
  }
  const minBeds = body.minBeds != null && body.minBeds !== '' ? Number(body.minBeds) : null
  if (minBeds != null && (!Number.isInteger(minBeds) || minBeds < 0)) {
    return c.json({ error: 'minBeds must be a non-negative integer' }, 400)
  }

  const alert = await prisma.dealAlert.create({
    data: {
      userId,
      district: community.slug,
      propertyType,
      maxPrice,
      minBeds,
      active: true,
    },
  })

  // Evaluate immediately so a new alert shows matches without waiting for the cron.
  const scan = await scanDealAlerts()
  return c.json({ alert, scan }, 201)
})

// DELETE /sqftlab/alerts/:id — matches cascade via the relation.
app.delete('/sqftlab/alerts/:id', async (c) => {
  const userId = getUserId(c)
  if (!userId) return unauthorized(c)

  const id = c.req.param('id')
  const existing = await prisma.dealAlert.findFirst({ where: { id, userId } })
  if (!existing) return c.json({ error: 'Alert not found' }, 404)

  await prisma.dealAlert.delete({ where: { id } })
  return c.json({ ok: true, deleted: id })
})

// POST /sqftlab/alerts/scan — run the engine on demand (the scraper cron also
// calls this after each listing upsert).
app.post('/sqftlab/alerts/scan', async (c) => {
  const scan = await scanDealAlerts()
  return c.json({ ok: true, scan })
})

// POST /sqftlab/alerts/notify — deliver unseen matches by email.
app.post('/sqftlab/alerts/notify', async (c) => {
  const result = await notifyPendingMatches()
  return c.json({ ok: true, notify: result })
})

// ─── Payment kill switch (spec Part 5.5) ──────────────────────────────────────
// Mirrors PAYMENTS_ENABLED in src/lib/payments.ts. Every payment endpoint must
// refuse explicitly — a bare 404 is indistinguishable from a typo in a client,
// and the spec requires these to answer 503 with a readable message.
const PAYMENTS_BLOCKED = {
  error: 'Payment processing is not yet available.',
  paymentsEnabled: false,
} as const

for (const path of ['/checkout', '/subscribe', '/create-payment-intent']) {
  app.all(path, (c) => c.json(PAYMENTS_BLOCKED, 503))
}

// Stripe webhooks are accepted and logged, never processed, so a delayed event
// cannot start a subscription behind the kill switch.
app.post('/webhooks/stripe', async (c) => {
  const body = await c.req.text().catch(() => '')
  console.info(
    `[sqftLab] Stripe webhook ignored (PAYMENTS_ENABLED=false) — ${body.length} bytes`,
  )
  return c.json({ received: true, processed: false })
})

// ═══════════════════════════════════════════════════════════════════════════
// Spec Part 6 / Part 8 — the 7 extraordinary intelligence products + the
// supporting district, macro and image endpoints.
// ═══════════════════════════════════════════════════════════════════════════

const SPEC_VERSION = '2.0'

// ─── 6.1 Real Price Index ────────────────────────────────────────────────────
// GET /api/sqftlab/rpi?district=downtown-dubai&type=Apartment&beds=2
app.get('/sqftlab/rpi', async (c) => {
  const district = c.req.query('district')
  const type = c.req.query('type')
  const bedsParam = c.req.query('beds')
  const beds = bedsParam === 'all' || bedsParam == null ? ALL_BEDS : Number(bedsParam)

  const where: Record<string, unknown> = {}
  if (district) where.district = district
  if (type) where.propertyType = type
  if (bedsParam != null) where.bedrooms = Number.isFinite(beds) ? beds : ALL_BEDS

  const latestDate = await prisma.realPriceIndex.findFirst({
    where: district ? { district } : {},
    orderBy: { indexDate: 'desc' },
    select: { indexDate: true },
  })

  const rows = await prisma.realPriceIndex.findMany({
    where: { ...where, ...(latestDate ? { indexDate: latestDate.indexDate } : {}) },
    orderBy: { indexValue: 'desc' },
    take: 200,
  })
  if (!rows.length) {
    return c.json({
      index: [],
      insufficientHistory: true,
      reason: 'No Real Price Index segments have been computed yet. Run POST /api/sqftlab/intelligence/run.',
      methodology: 'Trimmed mean (5th–95th percentile) of DLD-registered sales PSF. The window starts at the spec\'s 30 days and widens to 90/180/365 only when 30 days leaves too few segments above the 3-sale confidence floor. Segments under 3 sales are always omitted.',
      source: 'Dubai Land Department',
    })
  }

  const history = district
    ? await prisma.realPriceIndex.findMany({
        where: { district, ...(type ? { propertyType: type } : {}) },
        orderBy: { indexDate: 'desc' },
        take: 90,
      })
    : []

  const head = rows[0]
  const monthlyAgo = history.find((h) => h.indexDate.getTime() <= Date.now() - 30 * 86_400_000)
  const yearlyAgo = history.find((h) => h.indexDate.getTime() <= Date.now() - 365 * 86_400_000)
  const pct = (a?: number | null, b?: number | null) =>
    a == null || b == null || b === 0 ? null : ((a - b) / b) * 100

  return c.json({
    district: district ?? 'all',
    propertyType: type ?? 'All',
    bedrooms: head.bedrooms === ALL_BEDS || head.bedrooms < 0 ? null : head.bedrooms,
    indexValue: Math.round(head.indexValue),
    cpiAdjusted: head.cpiAdjusted != null ? Math.round(head.cpiAdjusted) : null,
    transactionCount: head.transactionCount,
    monthlyChange: pct(head.indexValue, monthlyAgo?.indexValue),
    yearlyChange: pct(head.indexValue, yearlyAgo?.indexValue),
    history: history.map((h) => ({
      date: h.indexDate.toISOString().slice(0, 10),
      indexValue: Math.round(h.indexValue),
      cpiAdjusted: h.cpiAdjusted != null ? Math.round(h.cpiAdjusted) : null,
      transactionCount: h.transactionCount,
    })),
    segments: rows.length,
    index: rows.slice(0, 60).map((r) => ({
      district: r.district, propertyType: r.propertyType,
      bedrooms: r.bedrooms < 0 ? null : r.bedrooms,
      indexValue: Math.round(r.indexValue),
      cpiAdjusted: r.cpiAdjusted != null ? Math.round(r.cpiAdjusted) : null,
      transactionCount: r.transactionCount,
    })),
    methodology: 'Trimmed mean (5th–95th percentile) of DLD-registered sales PSF. The window starts at the spec\'s 30 days and widens to 90/180/365 only when 30 days leaves too few segments above the 3-sale confidence floor. Segments under 3 sales are always omitted.',
    source: 'Dubai Land Department',
    calculatedAt: head.calculatedAt.toISOString(),
  })
})

// ─── 6.2 Building Intelligence Profile ──────────────────────────────────────
app.get('/sqftlab/building', async (c) => {
  const district = c.req.query('district')
  const community = c.req.query('community')
  const sort = c.req.query('sort') ?? 'score'
  const limit = Math.min(Number(c.req.query('limit') ?? 50) || 50, 200)

  const where: Record<string, unknown> = {}
  if (district) where.district = district
  if (community) where.communityEn = community

  const orderBy =
    sort === 'liquidity' ? { liquidityScore: 'desc' as const }
    : sort === 'trend' ? { psfTrend12m: 'desc' as const }
    : { intelligenceScore: 'desc' as const }

  const buildings = await prisma.buildingProfile.findMany({ where, orderBy, take: limit })
  // Count the actual input so an empty result can explain itself instead of
  // returning a bare 0 next to a claim of government provenance.
  const txnCount = await prisma.transaction.count()
  return c.json({
    buildings,
    count: buildings.length,
    ...(buildings.length === 0
      ? {
          insufficientData: true,
          reason:
            txnCount === 0
              ? 'No registered transactions have been loaded, so no building profiles can be computed. Connect a transaction source (DUBAI_PULSE_API_KEY for Dubai, or ADREC_API_URL/ADREC_API_KEY for Abu Dhabi).'
              : `No building profiles match this filter yet, though ${txnCount} transactions are available. Run the intelligence pipeline.`,
        }
      : {}),
    methodology:
      'Every metric is derived from registered sales in that building: price velocity from PSF windows, ' +
      'liquidity from median holding period between resales, owner confidence from units never resold, ' +
      'and floor premium from a PSF-on-floor regression.',
    source: txnCount > 0 ? 'Registered transactions' : null,
    transactionCount: txnCount,
  })
})

app.get('/sqftlab/building/:slug', async (c) => {
  const slug = decodeURIComponent(c.req.param('slug'))
  const [buildingNameEn, communityEn] = slug.includes('--') ? slug.split('--') : [slug, undefined]

  const building = communityEn
    ? await prisma.buildingProfile.findFirst({ where: { buildingNameEn, communityEn } })
    : await prisma.buildingProfile.findFirst({ where: { buildingNameEn } })

  if (!building) return c.json({ error: 'Building not found', slug }, 404)

  const peers = await prisma.buildingProfile.findMany({
    where: { communityEn: building.communityEn, NOT: { id: building.id } },
    orderBy: { intelligenceScore: 'desc' },
    take: 5,
  })

  return c.json({
    building,
    peers,
    interpretation: {
      psfVelocity: 'Is this building gaining or losing value faster than its community?',
      liquidity: 'How quickly a unit can be resold here — low means a slow exit.',
      ownerOccupier: 'Units never resold = stable, owner-occupied stock.',
      buyerHoldRate: 'Share of buyers who held longer than 12 months.',
      ejariDensity: 'Rental contracts per 100 DLD units — higher means rental-dominated.',
      floorPremium: building.floorPremiumPct != null
        ? `Each floor adds about ${building.floorPremiumPct.toFixed(2)}% to PSF — floor 20 vs floor 5 is roughly ${(15 * building.floorPremiumPct).toFixed(1)}% more.`
        : 'Not enough floor-tagged sales in this building to fit a premium curve.',
    },
  })
})

// ─── 6.3 District Yield Curve ───────────────────────────────────────────────
app.get('/sqftlab/yield-curve', async (c) => {
  const district = c.req.query('district')
  if (!district) return c.json({ error: 'district query parameter is required' }, 400)
  const result = await computeYieldCurve(district)
  if ('error' in result && result.error === 'district_not_found') {
    return c.json({ error: `Unknown district: ${district}` }, 404)
  }
  return c.json(result)
})

// ─── 6.4 Migration Signal ───────────────────────────────────────────────────
app.get('/sqftlab/migration', async (c) => {
  const district = c.req.query('district')
  const where = district ? { district } : {}

  const [flows, surges] = await Promise.all([
    prisma.nationalityFlow.findMany({
      where, orderBy: [{ month: 'desc' }, { transactionCount: 'desc' }], take: 100,
    }),
    migrationSurges(20),
  ])

  if (!flows.length) {
    return c.json({
      flows: [], surges: [], insufficientData: true,
      reason: 'No transactions carry buyerNationality. DLD populates this field; the current dataset does not.',
      methodology: 'Share of transactions by buyer nationality per district per month, with month-on-month surge detection above 25%.',
    })
  }
  return c.json({
    flows, surges,
    surgeThresholdPct: 25,
    methodology: 'Share of transactions by buyer nationality per district per month, with month-on-month surge detection above 25%.',
    source: 'Dubai Land Department buyer records',
  })
})

// ─── 6.5 Institutional Flow Tracker ─────────────────────────────────────────
app.get('/sqftlab/flow', async (c) => {
  const district = c.req.query('district')
  const clusters = await prisma.institutionalTransaction.findMany({
    where: district ? { district } : {},
    orderBy: { totalValue: 'desc' },
    take: 50,
  })
  if (!clusters.length) {
    return c.json({
      clusters: [], insufficientData: true,
      reason: 'No corporate buyer clusters found. This requires buyerType=corporate on DLD transactions.',
      methodology: 'Corporate purchases clustered by entity + building, split on any gap over 30 days, kept at 3+ units.',
    })
  }
  return c.json({
    clusters,
    count: clusters.length,
    totalValueAed: clusters.reduce((s, x) => s + x.totalValue, 0),
    methodology: 'Corporate purchases clustered by entity + building, split on any gap over 30 days, kept at 3+ units.',
    source: 'Dubai Land Department',
  })
})

// ─── 6.6 Construction Pipeline Pressure ─────────────────────────────────────
app.get('/sqftlab/supply', async (c) => {
  const rows = await prisma.supplyPipeline.findMany({ orderBy: { pressureScore: 'desc' } })
  if (!rows.length) {
    return c.json({
      districts: [], insufficientData: true,
      reason: 'Supply pipeline has not been computed yet. Run POST /api/sqftlab/intelligence/run.',
      methodology: 'Gross off-plan registrations in the trailing 3 years divided by trailing 12-month absorption, scaled to a 0–100 pressure score. Because a DLD row carries no unit identifier, registrations cannot be matched to completions, so the unit count is an upper bound.',
    })
  }
  return c.json({
    districts: rows,
    highestPressure: rows[0],
    lowestPressure: rows[rows.length - 1],
    methodology: 'Gross off-plan registrations in the trailing 3 years divided by trailing 12-month absorption, scaled to a 0–100 pressure score. Because a DLD row carries no unit identifier, registrations cannot be matched to completions, so the unit count is an upper bound.',
    source: 'Dubai Land Department off-plan records',
  })
})

// ─── 6.7 Economic Sensitivity + scenario modeller ───────────────────────────
app.get('/sqftlab/macro', async (c) => {
  const district = c.req.query('district')
  const rows = await prisma.macroSensitivity.findMany({ where: district ? { district } : {} })
  const indicators = await prisma.macroIndicator.findMany({ orderBy: { fetchedAt: 'desc' }, take: 40 })
  const latestFx = await prisma.exchangeRate.findFirst({ orderBy: { fetchedAt: 'desc' } })

  const required = ['oil_price', 'vix', 'uae_gdp', 'uae_tourism']
  const present = [...new Set(indicators.map((i) => i.indicator))]
  const missing = required.filter((i) => !present.includes(i))

  if (!rows.length) {
    return c.json({
      sensitivities: [], insufficientHistory: true,
      missingIndicators: missing,
      indicatorsAvailable: present,
      latestFx,
      reason:
        `The sensitivity model needs 20+ months of district PSF history plus aligned oil, VIX, GDP and tourism series. ` +
        (missing.length ? `No ${missing.join(', ')} series is ingested.` : ''),
      methodology: 'Multiple OLS regression of monthly district PSF on oil, VIX, UAE GDP and tourism arrivals.',
    })
  }
  return c.json({ sensitivities: rows, indicatorsAvailable: present, missingIndicators: missing, latestFx })
})

app.post('/sqftlab/macro/scenario', async (c) => {
  const body = await c.req.json().catch(() => ({})) as {
    district?: string; oilPct?: number; vixChange?: number; gdpPct?: number; tourismPct?: number
  }
  if (!body.district) return c.json({ error: 'district is required' }, 400)

  const s = await prisma.macroSensitivity.findFirst({ where: { district: body.district } })
  if (!s) {
    return c.json({
      error: 'No fitted sensitivity model for this district yet.',
      district: body.district,
      insufficientHistory: true,
      reason: 'The scenario modeller needs the regression coefficients, which require 20+ months of history.',
    }, 412)
  }
  return c.json({
    district: body.district,
    shock: { oilPct: body.oilPct ?? 0, vixChange: body.vixChange ?? 0, gdpPct: body.gdpPct ?? 0, tourismPct: body.tourismPct ?? 0 },
    ...applyScenario(s, body),
    rSquared: s.rSquared,
  })
})

// ─── District metrics + market summary ──────────────────────────────────────
app.get('/sqftlab/districts', async (c) => {
  const emirate = c.req.query('emirate')
  const metrics = await prisma.districtMetrics.findMany({ orderBy: { momentumScore: 'desc' } })
  const communities = await prisma.community.findMany({
    select: { slug: true, nameEn: true, nameAr: true, emirate: true, latitude: true, longitude: true, medianAedSqft: true, grossYieldPct: true, neighbourhoodScore: true },
  })
  const byslug = new Map(communities.map((x) => [x.slug, x]))

  const districts = metrics
    .map((m) => ({ ...m, community: byslug.get(m.district) ?? null }))
    .filter((m) => (emirate && emirate !== 'all' ? m.community?.emirate === emirate : true))

  return c.json({
    districts,
    count: districts.length,
    layers: ['psf', 'yield', 'momentum', 'dealDensity', 'supplyPressure', 'institutionalFlow'],
    methodology: 'Per-district roll-up of DLD sales over trailing windows, recomputed by the intelligence pipeline.',
  })
})

app.get('/sqftlab/market-summary', async (c) => {
  const summary = await prisma.marketSummary.findFirst({ orderBy: { computedAt: 'desc' } })
  if (!summary) {
    return c.json({
      insufficientData: true,
      reason: 'Market summary has not been computed yet. Run POST /api/sqftlab/intelligence/run.',
    })
  }
  const fx = await prisma.exchangeRate.findFirst({ orderBy: { fetchedAt: 'desc' } })
  return c.json({ summary, fx })
})

// ─── Hourly refresh cron ─────────────────────────────────────────────────────
//
// Nothing was scheduled: data only moved when someone called /scrape or
// /intelligence/run by hand, so the dashboard looked identical whether it had
// refreshed a minute ago or never. This is the job the scheduler calls hourly,
// and every execution is recorded in `CronRun`.
//
// The secret is read from the environment. It is deliberately NOT committed —
// this repository is public, and the legacy literal below is already public, so
// it is accepted only for backward compatibility and should be rotated.
const LEGACY_CRON_SECRET = 'sqftlab-cron-2026'

function cronAuthorized(c: Context): boolean {
  const provided = c.req.query('secret') ?? c.req.header('x-cron-secret') ?? ''
  if (!provided) return false
  const expected = process.env.CRON_SECRET
  return (!!expected && provided === expected) || provided === LEGACY_CRON_SECRET
}

const hourlyRefreshHandler = async (c: Context) => {
  if (!cronAuthorized(c)) return c.json({ error: 'unauthorized' }, 401)
  try {
    const result = await runHourlyRefresh()
    // 207 when some steps failed: the run happened, but the data is only
    // partially refreshed and a monitor should see that.
    return c.json(result, result.ok ? 200 : 207)
  } catch (e) {
    return c.json({ ok: false, error: e instanceof Error ? e.message : String(e) }, 500)
  }
}

// GET for a scheduler, POST for a manual trigger.
app.get('/sqftlab/cron/hourly', hourlyRefreshHandler)
app.post('/sqftlab/cron/hourly', hourlyRefreshHandler)

// Data freshness. Public on purpose: the UI needs to state honestly when data
// was last refreshed, and step detail stays behind the secret.
app.get('/sqftlab/cron/status', async (c) => {
  const runs = await recentCronRuns(10)
  const last = runs[0]
  const lastRunAt = last ? new Date(last.startedAt) : null
  const ageMs = lastRunAt ? Date.now() - lastRunAt.getTime() : null
  const staleAfterMs = 2 * 60 * 60 * 1000

  return c.json({
    job: HOURLY_JOB,
    expectedIntervalMs: 60 * 60 * 1000,
    lastRunAt,
    lastStatus: last?.status ?? null,
    lastDurationMs: last?.durationMs ?? null,
    ageMs,
    healthy: ageMs != null && ageMs < staleAfterMs,
    staleAfterMs,
    runCount: runs.length,
    ...(cronAuthorized(c) ? { runs } : {}),
  })
})

// Data provenance. Public and honest: each source reports whether it is
// configured and how much real data it has actually delivered, so the UI can
// state its sourcing truthfully instead of asserting "Real-time" unconditionally.
app.get('/sqftlab/sources', async (c) => {
  const [listingAgg, txnSources] = await Promise.all([
    prisma.listing.groupBy({
      by: ['source'],
      _count: { _all: true },
      _max: { scrapedAt: true },
    }),
    prisma.transaction.groupBy({
      by: ['source'],
      _count: { _all: true },
      _max: { registeredAt: true },
    }),
  ])

  const listingRows = listingAgg.map((r) => ({
    name: r.source,
    kind: 'listings' as const,
    records: r._count._all,
    lastRecordAt: r._max.scrapedAt,
  }))

  const txnRows = txnSources.map((r) => ({
    name: r.source,
    kind: 'transactions' as const,
    records: r._count._all,
    lastRecordAt: r._max.registeredAt,
  }))

  // "Available to fetch" is a different question from "has been fetched" — the
  // record counts answer the second, this answers the first.
  const available = [
    { name: 'PropertyFinder', kind: 'listings', requiresCredentials: false, envVar: null, connected: listingRows.some((r) => r.name === 'propertyfinder') },
    { name: 'DLD (Dubai Pulse)', kind: 'transactions', requiresCredentials: true, envVar: 'DUBAI_PULSE_API_KEY', connected: txnRows.some((r) => r.name === 'dld') },
    { name: 'ADREC (Abu Dhabi)', kind: 'transactions', requiresCredentials: true, envVar: 'ADREC_API_URL', connected: txnRows.some((r) => r.name === 'adrec') },
  ]

  return c.json({
    available,
    delivering: [...listingRows, ...txnRows],
    note: 'Counts are recorded rows only. Nothing here is estimated or generated.',
  })
})

// ─── Pipeline control (manual trigger; the hourly cron calls this too) ──────
app.post('/sqftlab/intelligence/run', async (c) => {
  try {
    const result = await runIntelligencePipeline()

    // Spec 16.3 — broadcast the recomputed state to every connected client.
    const summary = await prisma.marketSummary.findFirst({ orderBy: { computedAt: 'desc' } })
    if (summary) publish('market:update', summary)
    publish('intelligence:update', {
      rpi: result.rpi, buildings: result.buildings, supply: result.supply,
      migration: result.migration, flow: result.flow, metrics: result.metrics,
      durationMs: result.durationMs, generatedAt: result.generatedAt,
    })
    const topDistricts = await prisma.districtMetrics.findMany({
      orderBy: { momentumScore: 'desc' }, take: 10,
    })
    for (const d of topDistricts) {
      publish('district:update', {
        district: d.district, avgPricePsf: d.avgPricePsf,
        priceChange3m: d.priceChange3m, momentumScore: d.momentumScore,
        calculatedAt: d.calculatedAt.toISOString(),
      })
    }

    return c.json({ ...result, published: { market: !!summary, districts: topDistricts.length } })
  } catch (e) {
    return c.json({ ok: false, error: e instanceof Error ? e.message : String(e) }, 500)
  }
})

// Fire the broadcast path without recomputing, so the client can be exercised
// against a live stream even when nothing has changed on disk.
app.post('/sqftlab/stream/test-publish', async (c) => {
  const summary = await prisma.marketSummary.findFirst({ orderBy: { computedAt: 'desc' } })
  publish('market:update', summary ?? { note: 'no market summary computed yet' })
  const d = await prisma.districtMetrics.findFirst({ orderBy: { momentumScore: 'desc' } })
  if (d) publish('district:update', { district: d.district, momentumScore: d.momentumScore })
  const deal = await prisma.listing.findFirst({ where: { isDeal: true } })
  if (deal) {
    publish('deal:new', {
      id: deal.id, title: deal.title, purpose: deal.purpose,
      priceAed: deal.priceAed, pricePerSqft: deal.pricePerSqft,
      imageUrl: deal.imageUrl, sourceUrl: deal.sourceUrl,
      detectedAt: new Date().toISOString(),
    })
  }
  return c.json({ ok: true, published: ['market:update', 'district:update', 'deal:new'], ...streamStatus() })
})

app.get('/sqftlab/intelligence/status', async (c) => {
  const [rpi, buildings, flows, clusters, supply, sens, metrics, summary, macro, fx] = await Promise.all([
    prisma.realPriceIndex.count(), prisma.buildingProfile.count(),
    prisma.nationalityFlow.count(), prisma.institutionalTransaction.count(),
    prisma.supplyPipeline.count(), prisma.macroSensitivity.count(),
    prisma.districtMetrics.count(), prisma.marketSummary.count(),
    prisma.macroIndicator.count(), prisma.exchangeRate.count(),
  ])
  const lastSummary = await prisma.marketSummary.findFirst({ orderBy: { computedAt: 'desc' } })
  return c.json({
    products: {
      realPriceIndex: { rows: rpi, ready: rpi > 0 },
      buildingIntelligence: { rows: buildings, ready: buildings > 0 },
      migrationSignal: { rows: flows, ready: flows > 0 },
      institutionalFlow: { rows: clusters, ready: clusters > 0 },
      supplyPipeline: { rows: supply, ready: supply > 0 },
      macroSensitivity: { rows: sens, ready: sens > 0 },
      districtMetrics: { rows: metrics, ready: metrics > 0 },
    },
    infrastructure: { marketSummary: summary, macroIndicators: macro, exchangeRates: fx },
    lastComputedAt: lastSummary?.computedAt?.toISOString() ?? null,
    specVersion: SPEC_VERSION,
  })
})

// ─── Macro ingestion (spec Part 3.2 free sources) ───────────────────────────
app.post('/sqftlab/macro/refresh', async (c) => {
  try {
    const result = await fetchAllMacro()
    return c.json({ ...result, fetchedAt: new Date().toISOString() })
  } catch (e) {
    return c.json({ ok: false, error: e instanceof Error ? e.message : String(e) }, 500)
  }
})

app.get('/sqftlab/fx', async (c) => {
  const latest = await prisma.exchangeRate.findFirst({ orderBy: { fetchedAt: 'desc' } })
  if (latest) return c.json(latest)
  // Nothing ingested yet — fetch live rather than returning an empty shape.
  const r = await fetchExchangeRates()
  if (!r.ok) return c.json({ error: r.error ?? 'FX unavailable' }, 502)
  const fresh = await prisma.exchangeRate.findFirst({ orderBy: { fetchedAt: 'desc' } })
  return c.json(fresh)
})

// ─── Spec Part 8 — /api/img image proxy ─────────────────────────────────────
// Only hosts we actually scrape are allowed through: an open proxy here would
// be an SSRF hole pointed at the internal network.
const IMAGE_HOST_ALLOWLIST = [
  'bayut-production.s3.eu-central-1.amazonaws.com',
  'images.bayut.com',
  'cdn.propertyfinder.ae',
  'www.propertyfinder.ae',
  'dbz-images.dubizzle.com',
  'images.dubizzle.com',
]

app.get('/sqftlab/img', async (c) => {
  const raw = c.req.query('url')
  if (!raw) return c.json({ error: 'url query parameter is required' }, 400)

  let target: URL
  try {
    target = new URL(raw)
  } catch {
    return c.json({ error: 'url is not a valid absolute URL' }, 400)
  }
  if (target.protocol !== 'https:' || !IMAGE_HOST_ALLOWLIST.includes(target.hostname)) {
    return c.json({ error: `Host not allowed: ${target.hostname}`, allowlist: IMAGE_HOST_ALLOWLIST }, 403)
  }

  const cached = await prisma.imageCache.findFirst({ where: { externalUrl: target.toString() } })
  if (cached?.contentType && cached.expiresAt && cached.expiresAt.getTime() > Date.now()) {
    return c.body(null, 302, { Location: target.toString() })
  }

  try {
    const ctl = new AbortController()
    const timer = setTimeout(() => ctl.abort(), 12_000)
    const res = await fetch(target.toString(), { signal: ctl.signal, headers: { 'User-Agent': 'sqftLab/1.0' } })
    clearTimeout(timer)
    if (!res.ok) return c.json({ error: `Upstream returned ${res.status}` }, 502)

    const buf = Buffer.from(await res.arrayBuffer())
    const contentType = res.headers.get('content-type') ?? 'image/jpeg'
    await prisma.imageCache.upsert({
      where: { externalUrl: target.toString() },
      create: {
        externalUrl: target.toString(), contentType, sizeBytes: buf.length,
        expiresAt: new Date(Date.now() + 7 * 86_400_000),
      },
      update: { contentType, sizeBytes: buf.length, fetchedAt: new Date(), expiresAt: new Date(Date.now() + 7 * 86_400_000) },
    })
    return c.body(new Uint8Array(buf), 200, {
      'Content-Type': contentType,
      'Cache-Control': 'public, max-age=604800, immutable',
    })
  } catch (e) {
    return c.json({ error: e instanceof Error ? e.message : String(e) }, 502)
  }
})

// ═══════════════════════════════════════════════════════════════════════════
// Spec Part 16 — real-time stream (SSE).
// ═══════════════════════════════════════════════════════════════════════════

app.get('/sqftlab/stream/status', (c) => c.json(streamStatus()))

app.get('/sqftlab/stream/market', (c) =>
  streamSSE(c, async (stream) => {
    let closed = false

    // 1. Send the current state immediately so there is no empty first paint.
    const summary = await prisma.marketSummary.findFirst({ orderBy: { computedAt: 'desc' } })
    const fx = await prisma.exchangeRate.findFirst({ orderBy: { fetchedAt: 'desc' } })
    await stream.writeSSE({
      event: 'message',
      data: JSON.stringify({ type: 'init', payload: { summary, fx }, ts: Date.now() }),
    })

    // 2. Replay whatever was published before this client connected.
    for (const m of recentMessages()) {
      await stream.writeSSE({
        event: 'message',
        data: JSON.stringify({ type: m.channel, payload: m.payload, ts: m.ts }),
      })
    }

    // 3. Forward everything published from here on.
    const unsubscribe = subscribe(async (m) => {
      if (closed) return
      try {
        await stream.writeSSE({
          event: 'message',
          data: JSON.stringify({ type: m.channel, payload: m.payload, ts: m.ts }),
        })
      } catch {
        closed = true
        unsubscribe()
      }
    })

    // 4. Heartbeat — keeps proxies from closing an idle connection, and gives
    //    the client a liveness signal it can show in the UI.
    const heartbeat = setInterval(() => {
      if (closed) return
      stream.writeSSE({ event: 'ping', data: JSON.stringify({ ts: Date.now() }) }).catch(() => {
        closed = true
        unsubscribe()
        clearInterval(heartbeat)
      })
    }, 25_000)

    stream.onAbort(() => {
      closed = true
      clearInterval(heartbeat)
      unsubscribe()
    })

    // Keep the handler alive until the client disconnects.
    await new Promise<void>((resolve) => {
      stream.onAbort(resolve)
      setTimeout(resolve, 30 * 60 * 1000)
    })
  }),
)

// Catch-all — must be registered LAST so every real route wins.
//
// The pattern is '*' and not '/api/*': server.tsx mounts this app with
// `app.route('/api', customRoutes)`, so routes here are relative to that mount
// point (see the '/sqftlab/...' declarations above). An '/api/*' pattern would
// therefore never match anything.
//
// This exists because server.tsx also owns a SPA catch-all that resolves any
// unmatched path to index.html. Without this handler an API client asking for a
// mistyped or removed endpoint receives an HTML document with a 200 status,
// parses it as a successful response, and fails somewhere far away from the
// actual mistake. Answering in JSON keeps the failure at the boundary.
app.all('*', (c) =>
  c.json({ error: `No API route matches ${c.req.method} ${c.req.path}` }, 404),
)

export default app
