// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Hono Server
 *
 * Auto-generated by @shogo-ai/sdk
 * This file can be customized - it will not be overwritten if it exists.
 */

import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'
import customRoutes from './custom-routes'
import { createToolsHandlers } from '@shogo-ai/sdk/tools/server'

const app = new Hono()

// Health check endpoint
app.get('/health', (c) => c.json({ ok: true, timestamp: new Date().toISOString() }))

// CRUD routes (available after schema.prisma has models)
try {
  const { createAllRoutes } = await import('./src/generated')
  const { prisma } = await import('./src/lib/db')
  app.route('/api', createAllRoutes(prisma))
} catch {
  // No generated routes yet — CRUD routes will appear after schema.prisma is written
}

// Custom API routes (always mounted)
app.route('/api', customRoutes)

// Installed-integration tools proxy → forwards to the agent runtime
// using RUNTIME_AUTH_SECRET + RUNTIME_PORT (auto-detected from env).
const tools = createToolsHandlers({})
app.post('/api/tools/execute', (c) => tools.execute(c.req.raw))
app.get('/api/tools/schemas', (c) => tools.list(c.req.raw))

// SHOGO:CUSTOM-START asset-routing
// MUST be registered BEFORE the static handlers below. Hono dispatches in
// registration order, so anything mounted after the SPA catch-all is
// unreachable: that catch-all resolves *every* unmatched path to index.html and
// answers before a later middleware ever runs.
//
// `shogo generate` rewrites this file and RELOCATES this region to the bottom,
// below the SPA catch-all, where it silently stops working — the markers survive
// but the ordering does not. Editing prisma/schema.prisma is enough to trigger it.
// So after every schema change, check that this block still sits above the static
// handlers; if the canvas preview goes blank or a deploy serves a stale shell,
// look here first. `scripts/verify-server-routing.ts` asserts both behaviours
// below, and drops to 1/8 when this block has been moved.
//
// 1. The canvas preview mounts the app under /p/<projectId>/ and the client is
//    built with that base, so asset requests arrive with the prefix on the path.
//    Without this rewrite the browser receives index.html where it expects a JS
//    module, the bundle never executes and the page renders blank.
//
//    The build uses a RELATIVE base, so the same thing happens on any nested
//    client route: /auth/signin resolves `./assets/x.js` to /auth/assets/x.js.
//    Any nested path pointing at the assets directory is folded back to the root.
app.use('*', async (c, next) => {
  const url = new URL(c.req.url)
  let path = url.pathname

  const preview = path.match(/^\/p\/[A-Za-z0-9_-]+(\/.*)?$/)
  if (preview) path = preview[1] || '/'

  const nested = path.match(/^\/.+\/(assets\/.+)$/)
  if (nested) path = `/${nested[1]}`

  if (path === url.pathname) return next()
  url.pathname = path
  return app.fetch(new Request(url, c.req.raw))
})

// 2. index.html must revalidate; hashed assets may be cached forever. Vite gives
//    every build new asset filenames, so a cached shell is the only way a
//    correctly deployed UI stays invisible — the browser keeps loading the
//    previous build's asset names from cache.
app.use('*', async (c, next) => {
  await next()
  // The /api mount answers through custom-routes, which sets the security headers itself
  // (see the "Security headers (Day 17 Task E2)" block there). This branch is for the
  // responses that mount never sees — the SPA shell and its assets.
  //
  // It matters more here than on the API: X-Frame-Options is what stops this app being
  // framed by another site, and a JSON API is not what gets framed. Setting them only in
  // custom-routes left every rendered page without them.
  if (c.req.path.startsWith('/api/')) return
  try {
    c.header('X-Content-Type-Options', 'nosniff')
    c.header('X-Frame-Options', 'DENY')
    c.header('X-XSS-Protection', '1; mode=block')
    c.header('Referrer-Policy', 'strict-origin-when-cross-origin')
    c.header('Permissions-Policy', 'camera=(), microphone=(), geolocation=()')
    if (process.env.NODE_ENV === 'production') {
      c.header('Strict-Transport-Security', 'max-age=31536000; includeSubDomains')
    }
  } catch {
    // Response already committed (streaming) — best-effort, as elsewhere.
  }
  if (/\.(js|mjs|css|woff2?|ttf|eot|png|jpe?g|gif|svg|webp|avif|ico)$/i.test(c.req.path)) {
    c.header('Cache-Control', 'public, max-age=31536000, immutable')
  } else {
    c.header('Cache-Control', 'no-cache, must-revalidate')
    c.header('Pragma', 'no-cache')
  }
})
// SHOGO:CUSTOM-END

// Serve static files in production
app.use('/*', serveStatic({ root: './dist' }))
app.get('*', serveStatic({ path: './dist/index.html' }))

const port = Number(process.env.PORT) || 3001
console.log(`🚀 Server running on http://localhost:${port}`)

Bun.serve({ port, fetch: app.fetch })

