// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Hono Server
 *
 * Auto-generated by @shogo-ai/sdk
 * This file can be customized - it will not be overwritten if it exists.
 */

import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'
import customRoutes from './custom-routes'
import { createToolsHandlers } from '@shogo-ai/sdk/tools/server'

const app = new Hono()

// Health check endpoint
app.get('/health', (c) => c.json({ ok: true, timestamp: new Date().toISOString() }))

// CRUD routes (available after schema.prisma has models)
try {
  const { createAllRoutes } = await import('./src/generated')
  const { prisma } = await import('./src/lib/db')
  app.route('/api', createAllRoutes(prisma))
} catch {
  // No generated routes yet — CRUD routes will appear after schema.prisma is written
}

// Custom API routes (always mounted)
app.route('/api', customRoutes)

// Installed-integration tools proxy → forwards to the agent runtime
// using RUNTIME_AUTH_SECRET + RUNTIME_PORT (auto-detected from env).
const tools = createToolsHandlers({})
app.post('/api/tools/execute', (c) => tools.execute(c.req.raw))
app.get('/api/tools/schemas', (c) => tools.list(c.req.raw))

// SHOGO:CUSTOM-START asset-routing
// MUST be registered BEFORE the static handlers below. Hono dispatches in
// registration order, so anything mounted after the SPA catch-all is
// unreachable: that catch-all resolves *every* unmatched path to index.html and
// answers before a later middleware ever runs.
//
// `shogo generate` rewrites this file and strips this region (despite the header
// claiming otherwise). Re-add it after every schema change; if the canvas preview
// goes blank or a deploy serves a stale shell, look here first.
// `scripts/verify-server-routing.ts` asserts both behaviours below.
//
// 1. The canvas preview mounts the app under /p/<projectId>/ and the client is
//    built with that base, so asset requests arrive with the prefix on the path.
//    Without this rewrite the browser receives index.html where it expects a JS
//    module, the bundle never executes and the page renders blank.
app.use('*', async (c, next) => {
  const m = c.req.path.match(/^\/p\/[A-Za-z0-9_-]+(\/.*)?$/)
  if (!m) return next()
  const url = new URL(c.req.url)
  url.pathname = m[1] || '/'
  return app.fetch(new Request(url, c.req.raw))
})

// 2. index.html must revalidate; hashed assets may be cached forever. Vite gives
//    every build new asset filenames, so a cached shell is the only way a
//    correctly deployed UI stays invisible — the browser keeps loading the
//    previous build's asset names from cache.
app.use('*', async (c, next) => {
  await next()
  if (c.req.path.startsWith('/api/')) return
  if (/\.(js|mjs|css|woff2?|ttf|eot|png|jpe?g|gif|svg|webp|avif|ico)$/i.test(c.req.path)) {
    c.header('Cache-Control', 'public, max-age=31536000, immutable')
  } else {
    c.header('Cache-Control', 'no-cache, must-revalidate')
    c.header('Pragma', 'no-cache')
  }
})
// SHOGO:CUSTOM-END

// Serve static files in production — AFTER the middleware above, so the prefix
// rewrite and cache headers actually apply to these responses.
app.use('/*', serveStatic({ root: './dist' }))
app.get('*', serveStatic({ path: './dist/index.html' }))

const port = Number(process.env.PORT) || 3001
console.log(`🚀 Server running on http://localhost:${port}`)

Bun.serve({ port, fetch: app.fetch })
